-- Append inside rollback-only migration transaction; uses exclusively synthetic queue rows.
DO $fixture$ DECLARE p jsonb;r jsonb; aid uuid:='00000000-0000-4000-8000-00000000a121'; jid uuid:='00000000-0000-4000-8000-00000000a122'; BEGIN
IF ccpun_admin.marketing_window('this_week','2026-09-24')->>'previousStart'<>'2026-09-14' OR ccpun_admin.marketing_window('this_week','2026-09-24')->>'previousEnd'<>'2026-09-17' THEN RAISE EXCEPTION 'EQUIVALENT_WEEKDAY_FAIL';END IF;
IF ccpun_admin.marketing_window_calendar('this_week','2026-09-24','2026-09-28')->>'currentStart'<>'2026-09-28' OR ccpun_admin.marketing_window_calendar('this_week','2026-09-24','2026-09-28')->>'availability'<>'no_mature_data' OR ccpun_admin.marketing_window_calendar('this_month','2026-09-28','2026-10-01')->>'currentStart'<>'2026-10-01' OR ccpun_admin.marketing_coverage('ga4-content-events','2026-09-28','2026-09-24') THEN RAISE EXCEPTION 'BUSINESS_CALENDAR_NO_MATURE_DATA_FAIL';END IF;
p:=jsonb_build_object('promptVersion','marketing-performance-v1','analysisType','weekly_performance','snapshotHash',repeat('a',64),'sourceManifestHash',repeat('b',64),'period',jsonb_build_object('key','this_week','currentStart','2026-09-21','currentEnd','2026-09-24'),'evidence',jsonb_build_array(jsonb_build_object('id','e1')),'coverage',jsonb_build_object('prepared',1,'sent',1,'dropped',0));
r:=ccpun_admin.admin_prepare_marketing_analysis(aid,p,repeat('c',64),'[]');IF r->>'status'<>'prepared' OR (r->>'reused')::boolean THEN RAISE EXCEPTION 'PREPARE_FAIL';END IF;
r:=ccpun_admin.admin_prepare_marketing_analysis(gen_random_uuid(),p,repeat('c',64),'[]');IF NOT(r->>'reused')::boolean OR r->>'analysisId'<>aid::text THEN RAISE EXCEPTION 'IDEMPOTENCY_FAIL';END IF;
r:=ccpun_admin.admin_marketing_analysis_status(aid);IF r->>'status'<>'prepared' OR (r->>'workerSucceeded')::boolean THEN RAISE EXCEPTION 'PREPARED_NOT_READY_FAIL';END IF;
INSERT INTO ccpun_admin.local_ai_job(job_id,task_type,data_class,ciphertext_b64,nonce_b64,auth_tag_b64,key_version,idempotency_key,actor_digest,request_fingerprint,queue_class,priority,deadline_at) VALUES(jid,'marketing-analysis','public-safe','synthetic-encrypted-placeholder',repeat('x',24),repeat('x',24),1,repeat('d',64),repeat('e',64),repeat('c',64),'batch',20,now()+interval '6 hours');
UPDATE ccpun_admin.marketing_analysis SET job_id=jid WHERE analysis_id=aid;
r:=ccpun_admin.admin_marketing_analysis_status(aid);IF r->>'status'<>'queued' OR (r->>'workerSucceeded')::boolean THEN RAISE EXCEPTION 'QUEUED_NOT_READY_FAIL';END IF;
UPDATE ccpun_admin.local_ai_job SET status='succeeded',review_status='pending',output_json=p,output_digest=repeat('f',64),completed_at=now(),model_name='qwen3:1.7b' WHERE job_id=jid;
r:=ccpun_admin.admin_marketing_analysis_status(aid);IF r->>'status'='ready' OR NOT(r->>'workerSucceeded')::boolean THEN RAISE EXCEPTION 'WORKER_SUCCESS_NOT_VALIDATED_FAIL';END IF;
BEGIN PERFORM ccpun_admin.admin_validate_marketing_analysis(aid,repeat('a',64));RAISE EXCEPTION 'WRONG_DIGEST_ACCEPTED';EXCEPTION WHEN OTHERS THEN IF SQLERRM='WRONG_DIGEST_ACCEPTED' THEN RAISE;END IF;END;
r:=ccpun_admin.admin_validate_marketing_analysis(aid,repeat('f',64));IF r->>'status'<>'ready' THEN RAISE EXCEPTION 'VALIDATION_PERSIST_FAIL';END IF;
r:=ccpun_admin.admin_read_marketing_analysis('this_week');IF r#>>'{lastGood,analysisId}'<>aid::text OR r#>'{lastGood,output}' IS NULL THEN RAISE EXCEPTION 'LAST_GOOD_FAIL';END IF;
IF has_table_privilege('ccpun_admin_runtime','ccpun_admin.marketing_analysis','SELECT') OR has_function_privilege('ccpun_local_ai_runtime','ccpun_admin.admin_validate_marketing_analysis(uuid,text)','EXECUTE') THEN RAISE EXCEPTION 'PRIVILEGE_FAIL';END IF;
PERFORM ccpun_admin.admin_read_marketing_v2('rolling_7',now());
RAISE NOTICE 'MARKETING_AI_FIXTURE_PASS';END $fixture$;
DO $measurement_fixture$ DECLARE e date:=(now() AT TIME ZONE 'America/Los_Angeles')::date-3;act jsonb;pid uuid;bid uuid:='00000000-0000-4000-8000-00000000b121';bid2 uuid:='00000000-0000-4000-8000-00000000b122';BEGIN
PERFORM ccpun_admin.admin_sync_marketing_identity(jsonb_build_array(jsonb_build_object('assetId','site:measurement-fixture','canonicalUrl','https://ccpun.com/measurement-fixture','title','Synthetic measurement','category','UAT','topic',NULL,'searchIntent',NULL,'contentType','test','publishedAt',NULL,'status','published','revision','synthetic-v1','aliases',jsonb_build_array(jsonb_build_object('url','https://ccpun.com/measurement-fixture','method','site-route')))));
act:=ccpun_admin.admin_save_marketing_action(jsonb_build_object('version',0,'assetId','site:measurement-fixture','priority','medium','actionType','investigation','description','Synthetic measurement fixture','expectedMetric','organic_sessions','owner','UAT','status','measuring','executedAt',(e-7)::timestamptz,'measurementDays',7,'notes','','hypothesis','','confounderNotes',''));
pid:=(act->>'id')::uuid;
-- UAT has no complete GA4 daily history before this fixture.
IF(SELECT baseline_covered FROM ccpun_admin.marketing_action WHERE action_id=pid) THEN RAISE EXCEPTION 'INCOMPLETE_BASELINE_PINNED';END IF;
INSERT INTO ccpun_admin.analytics_daily_batch(batch_id,source,collection_date,collection_key,status,completed_at) VALUES(bid,'ga4',current_date,'uat:measurement-1','completed',now());
INSERT INTO ccpun_admin.marketing_report_manifest(batch_id,report,resource_scope,period_start,period_end,source_as_of_date,source_as_of,collected_at,source_timezone,raw_sha256,complete,limitations) VALUES(bid,'ga4-daily-organic','properties/fixture',e-14,e,e,e::text,now(),'Asia/Bangkok',repeat('a',64),true,'[]');
INSERT INTO ccpun_admin.marketing_ga4_acquisition_daily(batch_id,report,resource_scope,day,source_medium,campaign,landing_page,sessions,engaged_sessions) SELECT bid,'ga4-daily-organic','properties/fixture',d::date,'organic','','/measurement-fixture',1,1 FROM generate_series(e-14,e,interval '1 day')d;
PERFORM ccpun_admin.admin_capture_marketing_measurements();IF(SELECT baseline_value FROM ccpun_admin.marketing_action WHERE action_id=pid)<>7 OR NOT(SELECT baseline_covered FROM ccpun_admin.marketing_action WHERE action_id=pid) THEN RAISE EXCEPTION 'DEFERRED_MATURE_BASELINE_FAIL';END IF;
IF(SELECT(observation->>'result')::numeric FROM ccpun_admin.marketing_action_measurement WHERE action_id=pid)<>7 THEN RAISE EXCEPTION 'POST_MEASUREMENT_FAIL';END IF;
INSERT INTO ccpun_admin.analytics_daily_batch(batch_id,source,collection_date,collection_key,status,completed_at) VALUES(bid2,'ga4',current_date,'uat:measurement-2','completed',now());
INSERT INTO ccpun_admin.marketing_report_manifest SELECT bid2,report,resource_scope,period_start,period_end,source_as_of_date,source_as_of_ts,source_as_of,collected_at+interval '1 second',source_timezone,repeat('b',64),complete,limitations,definition_version FROM ccpun_admin.marketing_report_manifest WHERE batch_id=bid;
INSERT INTO ccpun_admin.marketing_ga4_acquisition_daily SELECT bid2,report,resource_scope,day,source_medium,campaign,landing_page,100,100,key_events,session_key_event_rate FROM ccpun_admin.marketing_ga4_acquisition_daily WHERE batch_id=bid;
PERFORM ccpun_admin.admin_capture_marketing_measurements();IF(SELECT baseline_value FROM ccpun_admin.marketing_action WHERE action_id=pid)<>7 OR(SELECT(observation->>'result')::numeric FROM ccpun_admin.marketing_action_measurement WHERE action_id=pid)<>7 THEN RAISE EXCEPTION 'IMMUTABLE_MEASUREMENT_FAIL';END IF;
RAISE NOTICE 'MARKETING_MEASUREMENT_FIXTURE_PASS';END $measurement_fixture$;

-- Rollback-only native fixture; no provider call or permanent synthetic data.
DO $guard_fixture$ DECLARE d jsonb;m jsonb;r record;b1 uuid:='93000000-0000-4000-8000-000000000001';b2 uuid:='93000000-0000-4000-8000-000000000002';BEGIN
IF ccpun_admin.marketing_coverage('gsc-daily-page','2026-09-28','2026-09-24') IS DISTINCT FROM false THEN RAISE EXCEPTION 'REVERSED_COVERAGE_MUST_BE_FALSE';END IF;
INSERT INTO ccpun_admin.analytics_daily_batch(batch_id,source,collection_date,collection_key,status,completed_at) VALUES(b1,'gsc',current_date,'uat:marketing-guardrail-v3-1','completed',now()),(b2,'gsc',current_date,'uat:marketing-guardrail-v3-2','completed',now());
INSERT INTO ccpun_admin.marketing_report_manifest(batch_id,report,resource_scope,period_start,period_end,source_as_of_date,source_as_of,collected_at,source_timezone,raw_sha256,complete,limitations) VALUES(b1,'gsc-daily-page','sc-domain:guardrail-fixture','2026-08-01','2026-09-20','2026-09-20','2026-09-20','2026-09-20T12:00:00Z','America/Los_Angeles',repeat('a',64),true,'[]'),(b2,'gsc-daily-page','sc-domain:guardrail-fixture','2026-09-21','2026-09-27','2026-09-27','2026-09-27','2026-09-27T12:00:00Z','America/Los_Angeles',repeat('b',64),true,'[]');
INSERT INTO ccpun_admin.marketing_gsc_daily(batch_id,report,resource_scope,day,page,query,clicks,impressions,average_position) SELECT CASE WHEN day::date<='2026-09-20' THEN b1 ELSE b2 END,'gsc-daily-page','sc-domain:guardrail-fixture',day::date,'https://ccpun.com/guardrail-fixture','',CASE WHEN day::date>='2026-09-21' THEN 2 ELSE 1 END,100,5 FROM generate_series('2026-08-01'::date,'2026-09-27',interval '1 day') day;
FOR r IN SELECT * FROM(VALUES('this_week','2026-09-28T00:00:00Z'::timestamptz),('this_month','2026-10-01T00:00:00Z'::timestamptz))v(window_key,cutoff) LOOP
d:=ccpun_admin.admin_read_marketing_v2(r.window_key,r.cutoff);IF d#>>'{window,availability}'<>'no_mature_data' THEN RAISE EXCEPTION 'EXPECTED_NO_MATURE_DATA';END IF;
FOR m IN SELECT value FROM jsonb_array_elements(d->'kpis') LOOP IF m->>'current' IS NOT NULL OR m->>'coverageStatus'='complete' OR m->>'sampleStatus'<>'insufficient_data' THEN RAISE EXCEPTION 'NO_MATURE_DATA_CANNOT_BE_ZERO_OR_COMPLETE';END IF;END LOOP;
END LOOP;
d:=ccpun_admin.admin_read_marketing_v2('last_week','2026-09-28T00:00:00Z');IF d#>>'{window,currentStart}'<>'2026-09-21' OR d#>>'{window,currentEnd}'<>'2026-09-24' OR d#>>'{window,previousStart}'<>'2026-09-14' OR d#>>'{window,previousEnd}'<>'2026-09-17' THEN RAISE EXCEPTION 'VALID_PRIOR_WINDOW_MISALIGNED';END IF;
IF NOT ccpun_admin.marketing_coverage('gsc-daily-page','2026-09-14','2026-09-17') THEN RAISE EXCEPTION 'VALID_WINDOW_COVERAGE_FALSE';END IF;
m:=ccpun_admin.marketing_metric_record('search_clicks',8,4,true,true,'fixture');IF(m->>'current')::numeric<>8 OR(m->>'previous')::numeric<>4 OR(m->>'absoluteChange')::numeric<>4 THEN RAISE EXCEPTION 'VALID_COMPARISON_ALTERED';END IF;
IF(SELECT sum(clicks) FROM ccpun_admin.marketing_gsc_current WHERE resource_scope='sc-domain:guardrail-fixture' AND day BETWEEN '2026-09-14' AND '2026-09-17')<>4 THEN RAISE EXCEPTION 'VALID_PREVIOUS_NATIVE_FACTS_ALTERED';END IF;
RAISE NOTICE 'MARKETING_V2_DASHBOARD_BOUNDARY_FIXTURE_PASS';END $guard_fixture$;
