-- Rollback-only synthetic fixture. Run after migration body in the same UAT transaction.
-- No provider calls, customer data, real action or permanent fixture survives rollback.
DO $fixture$
DECLARE end_day date:=(now() AT TIME ZONE 'America/Los_Angeles')::date-3;w jsonb;cs date;ce date;ps date;pe date;rows jsonb;data jsonb;dashboard jsonb;first_action jsonb;result jsonb;payload jsonb;b1 uuid:='91000000-0000-4000-8000-000000000001';b2 uuid:='91000000-0000-4000-8000-000000000002';n integer;
BEGIN
 w:=ccpun_admin.marketing_window('rolling_7',end_day);cs:=(w->>'currentStart')::date;ce:=(w->>'currentEnd')::date;ps:=(w->>'previousStart')::date;pe:=(w->>'previousEnd')::date;
 IF ccpun_admin.marketing_window('this_month','2026-09-24')->>'previousEnd'<>'2026-08-24' THEN RAISE EXCEPTION 'MTD_EQUAL_ELAPSED_FAILED'; END IF;
 IF ccpun_admin.marketing_window('this_week','2026-09-24')->>'currentStart'<>'2026-09-21' THEN RAISE EXCEPTION 'MONDAY_WEEK_FAILED'; END IF;
 IF (ccpun_admin.marketing_metric_record('search_clicks',3,1,true,true,'test')->>'sampleStatus')<>'insufficient_data' OR ccpun_admin.marketing_metric_record('search_clicks',20,0,true,true,'test')->>'percentageChange' IS NOT NULL THEN RAISE EXCEPTION 'SAMPLE_OR_ZERO_BASELINE_FAILED'; END IF;
 PERFORM ccpun_admin.admin_sync_marketing_identity(jsonb_build_array(jsonb_build_object('assetId','site:fixture-a','canonicalUrl','https://ccpun.com/fixture-a','title','Synthetic A','category','UAT','topic',NULL,'searchIntent',NULL,'contentType','test','publishedAt',NULL,'status','published','revision','synthetic-v1','aliases',jsonb_build_array(jsonb_build_object('url','https://ccpun.com/fixture-a','method','site-route'))),jsonb_build_object('assetId','site:fixture-b','canonicalUrl','https://ccpun.com/fixture-b','title','Synthetic B','category','UAT','topic',NULL,'searchIntent',NULL,'contentType','test','publishedAt',NULL,'status','published','revision','synthetic-v1','aliases',jsonb_build_array(jsonb_build_object('url','https://ccpun.com/fixture-b','method','site-route')))));
 INSERT INTO ccpun_admin.analytics_daily_batch(batch_id,source,collection_date,collection_key,status,completed_at) VALUES(b1,'gsc',(now() AT TIME ZONE 'Asia/Bangkok')::date,'uat:marketing-fixture-1','completed',now()),(b2,'gsc',(now() AT TIME ZONE 'Asia/Bangkok')::date,'uat:marketing-fixture-2','completed',now());
 SELECT jsonb_agg(jsonb_build_object('วันที่',d::date,'หน้าเว็บ','https://ccpun.com/fixture-'||asset,'คลิก',CASE WHEN asset='a' THEN CASE WHEN d::date>=cs THEN 3 ELSE 2 END ELSE CASE WHEN d::date>=cs THEN 1 ELSE 4 END END,'การแสดงผล',100,'อันดับเฉลี่ย',5)) INTO rows FROM generate_series(end_day-55,end_day,interval '1 day') d CROSS JOIN unnest(ARRAY['a','b']) asset;
 data:=jsonb_build_object('resourceScope','sc-domain:fixture.ccpun.com','batchId',b1,'source','gsc','report','gsc-daily-page','windowStart',end_day-55,'windowEnd',end_day,'sourceAsOf',end_day,'collectedAt',now()-interval '2 minutes','nativeTimeZone','America/Los_Angeles','rawHash',repeat('a',64),'truncated',false,'limitations','[]'::jsonb,'rows',rows);
 INSERT INTO ccpun_admin.analytics_completed_report(batch_id,report,data) VALUES(b1,'gsc-daily-page',data);
 SELECT count(*) INTO n FROM ccpun_admin.marketing_gsc_daily WHERE batch_id=b1;PERFORM ccpun_admin.marketing_project_report(b1,'gsc-daily-page',data);IF (SELECT count(*) FROM ccpun_admin.marketing_gsc_daily WHERE batch_id=b1)<>n THEN RAISE EXCEPTION 'IDEMPOTENCY_FAILED';END IF;
 dashboard:=ccpun_admin.admin_read_marketing('rolling_7',now());IF (SELECT (x->>'current')::numeric FROM jsonb_array_elements(dashboard->'kpis') x WHERE x->>'metric'='search_clicks')<>28 THEN RAISE EXCEPTION 'CURRENT_RECONCILIATION_FAILED';END IF;
 IF (SELECT (x->>'previous')::numeric FROM jsonb_array_elements(dashboard->'kpis') x WHERE x->>'metric'='search_clicks')<>42 THEN RAISE EXCEPTION 'PREVIOUS_RECONCILIATION_FAILED';END IF;
 IF (SELECT x->'rows'->0->>'assetId' FROM jsonb_array_elements(dashboard->'leaderboards') x WHERE x->>'id'='search_clicks')<>'site:fixture-a' THEN RAISE EXCEPTION 'TOP10_ORDERING_FAILED';END IF;
 SELECT jsonb_agg(jsonb_build_object('วันที่',d::date,'หน้าเว็บ','https://ccpun.com/fixture-b','คลิก',1,'การแสดงผล',100,'อันดับเฉลี่ย',5)) INTO rows FROM generate_series(cs,ce,interval '1 day') d;
 data:=data||jsonb_build_object('batchId',b2,'windowStart',cs,'windowEnd',ce,'collectedAt',now()-interval '1 minute','rawHash',repeat('b',64),'rows',rows);
 INSERT INTO ccpun_admin.analytics_completed_report(batch_id,report,data) VALUES(b2,'gsc-daily-page',data);
 IF EXISTS(SELECT 1 FROM ccpun_admin.marketing_gsc_current WHERE resource_scope='sc-domain:fixture.ccpun.com' AND day BETWEEN cs AND ce AND page='https://ccpun.com/fixture-a') THEN RAISE EXCEPTION 'REMOVED_KEY_REVISION_FAILED';END IF;
 IF (SELECT count(*) FROM ccpun_admin.marketing_gsc_daily WHERE batch_id=b1)<>112 THEN RAISE EXCEPTION 'IMMUTABLE_HISTORY_FAILED';END IF;
 payload:=jsonb_build_object('version',0,'assetId','site:fixture-a','priority','medium','actionType','investigation','description','Synthetic reviewed action','expectedMetric','search_clicks','owner','UAT','status','planned','executedAt',NULL,'measurementDays',14,'notes','Human preserved note','hypothesis','Synthetic hypothesis','confounderNotes','No causal claim');
 first_action:=ccpun_admin.admin_save_marketing_action(payload);payload:=payload||jsonb_build_object('id',first_action->>'id','version',1,'status','doing');PERFORM ccpun_admin.admin_save_marketing_action(payload);
 BEGIN PERFORM ccpun_admin.admin_save_marketing_action(payload);RAISE EXCEPTION 'CAS_SHOULD_REJECT';EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE '%MARKETING_ACTION_CONFLICT%' THEN RAISE;END IF;END;
 payload:=payload-'id';payload:=payload||jsonb_build_object('version',0,'description','Synthetic Sheet action','importKey','draft:uat:1');result:=ccpun_admin.admin_import_marketing_actions(jsonb_build_object('spreadsheetId','1zpXXHuQ152wSZXdHb0yFJPVcdQiGOHvz4Yhxrmjdo-o','rows',jsonb_build_array(payload)));IF result->'results'->0->>'status'<>'created' THEN RAISE EXCEPTION 'SHEET_CREATE_FAILED';END IF;
 result:=ccpun_admin.admin_import_marketing_actions(jsonb_build_object('spreadsheetId','1zpXXHuQ152wSZXdHb0yFJPVcdQiGOHvz4Yhxrmjdo-o','rows',jsonb_build_array(payload)));IF result->'results'->0->>'status'<>'unchanged' THEN RAISE EXCEPTION 'SHEET_IDEMPOTENCY_FAILED';END IF;
 result:=ccpun_admin.admin_import_marketing_actions(jsonb_build_object('spreadsheetId','1zpXXHuQ152wSZXdHb0yFJPVcdQiGOHvz4Yhxrmjdo-o','rows',jsonb_build_array(payload||jsonb_build_object('notes','New human edit without revision'))));IF result->>'preserveActionPlan'<>'true' THEN RAISE EXCEPTION 'SHEET_CONFLICT_PRESERVATION_FAILED';END IF;
 IF has_table_privilege('ccpun_admin_runtime','ccpun_admin.marketing_gsc_daily','SELECT') OR EXISTS(SELECT 1 FROM pg_proc p CROSS JOIN LATERAL aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE p.oid='ccpun_admin.admin_read_marketing(text,timestamptz)'::regprocedure AND acl.grantee=0 AND acl.privilege_type='EXECUTE') THEN RAISE EXCEPTION 'PRIVILEGE_BOUNDARY_FAILED';END IF;
 RAISE NOTICE 'MARKETING_FIXTURE_PASS: current/previous/top10/revision/history/CAS/Sheet rerun/conflict/privacy grants';
END $fixture$;
