SELECT
 EXISTS(SELECT 1 FROM private_line.schema_migration WHERE version='20260918_line_safe_knowledge_crm_campaign_v1_production' AND checksum='sha256:099a8968a8ec6fbb1fee589b410f3f071e762dd86ef3b1906b903fed5029e68d') AS checksum_ok,
 EXISTS(SELECT 1 FROM private_line.system_identity WHERE singleton=true AND project_id='lively-bar-43618798' AND branch_id='br-long-resonance-b3ys5xrv' AND endpoint_id='ep-broad-butterfly-b3ro7u8w' AND database_name='neondb' AND migration_version='20260917_private_line_runtime_v1_production') AS base_identity_unchanged,
 to_regclass('private_line.advisor_private_note') IS NOT NULL AS note_table_exists,
 to_regclass('private_line.line_campaign') IS NOT NULL AS campaign_table_exists,
 to_regclass('private_line.line_campaign_delivery') IS NOT NULL AS delivery_table_exists,
 to_regclass('private_line.advisor_document_safe') IS NOT NULL AS document_safe_exists,
 to_regclass('private_line.line_campaign_safe') IS NOT NULL AS campaign_safe_exists,
 has_function_privilege('ccpun_admin_runtime','private_line.admin_read_advisor_inbox_filtered(jsonb,integer)','EXECUTE') AS admin_filter_execute,
 has_function_privilege('ccpun_admin_runtime','private_line.admin_update_case_operations(jsonb)','EXECUTE') AS admin_case_update_execute,
 has_function_privilege('ccpun_admin_runtime','private_line.admin_add_private_note(jsonb)','EXECUTE') AS admin_note_execute,
 has_function_privilege('ccpun_admin_runtime','private_line.admin_upsert_line_campaign(jsonb)','EXECUTE') AS admin_campaign_write_execute,
 has_function_privilege('ccpun_admin_runtime','private_line.admin_enqueue_line_campaign(jsonb)','EXECUTE') AS admin_campaign_enqueue_execute,
 has_function_privilege('ccpun_admin_runtime','private_line.admin_claim_line_campaign_delivery(jsonb)','EXECUTE') AS admin_campaign_claim_execute,
 has_function_privilege('ccpun_admin_runtime','private_line.admin_checkpoint_line_campaign_delivery(jsonb)','EXECUTE') AS admin_campaign_checkpoint_execute,
 NOT has_function_privilege('ccpun_line_ingress','private_line.admin_add_private_note(jsonb)','EXECUTE') AS ingress_note_denied,
 NOT has_function_privilege('ccpun_line_ingress','private_line.admin_enqueue_line_campaign(jsonb)','EXECUTE') AS ingress_campaign_denied,
 NOT has_function_privilege('ccpun_line_ingress','private_line.admin_claim_line_campaign_delivery(jsonb)','EXECUTE') AS ingress_campaign_claim_denied,
 NOT EXISTS (SELECT 1 FROM information_schema.role_table_grants g JOIN information_schema.tables t ON t.table_schema=g.table_schema AND t.table_name=g.table_name WHERE g.grantee='ccpun_admin_runtime' AND g.table_schema='private_line' AND t.table_type='BASE TABLE') AS admin_no_base_table_grants,
 NOT EXISTS (SELECT 1 FROM information_schema.role_table_grants g JOIN information_schema.tables t ON t.table_schema=g.table_schema AND t.table_name=g.table_name WHERE g.grantee='ccpun_line_ingress' AND g.table_schema='private_line' AND t.table_type='BASE TABLE') AS ingress_no_base_table_grants,
 has_function_privilege('ccpun_line_ingress','private_line.ingest_line_event(jsonb)','EXECUTE') AS ingress_ingest_unchanged;
