BEGIN;
SET LOCAL lock_timeout='5s';
SELECT 1 / CASE WHEN current_database()='neondb' THEN 1 ELSE 0 END AS database_guard;
SELECT 1 / CASE WHEN EXISTS(SELECT 1 FROM pg_roles WHERE rolname='ccpun_admin_runtime' AND NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole AND NOT rolbypassrls) THEN 1 ELSE 0 END AS role_guard;
SELECT 1 / CASE WHEN EXISTS(SELECT 1 FROM ccpun_admin.local_ai_identity WHERE singleton=true AND database_name='neondb' AND migration_version='20260919_local_ai_control_plane_v1' AND migration_checksum='sha256:b49fe8d024c279710eb4eb3b45b06e40ffc960a3ec57b21792c63c98514ceef6' AND ((lane='uat' AND project_id='young-term-47483330' AND branch_id='br-crimson-mouse-az7ajkv8' AND endpoint_id='ep-mute-frost-aztvz394') OR (lane='production' AND project_id='lively-bar-43618798' AND branch_id='br-long-resonance-b3ys5xrv' AND endpoint_id='ep-broad-butterfly-b3ro7u8w'))) THEN 1 ELSE 0 END AS identity_guard;
SELECT 1 / CASE WHEN EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version='20260920_local_ai_production_operations_v2' AND checksum='sha256:deb9f6761364a61bae275d5226f341ca021087da4116bc3f4703bd8b8c46fb1f') THEN 1 ELSE 0 END AS prerequisite_guard;
SELECT 1 / CASE WHEN EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version='20260927_analytics_local_review_v3' AND checksum='sha256:df860b9218c535786bbdc3d6459e18cc76d76e6ea3b35c3d5e1ef64241b5d5ca') THEN 1 ELSE 0 END AS v3_guard;
SELECT pg_advisory_xact_lock(hashtext('ccpun_admin:20260927_marketing_local_analysis_v2'));
SELECT 1 / CASE WHEN NOT EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version='20260927_marketing_local_analysis_v2' AND checksum<>'sha256:eb0d7a8a1637ccde4bc17d5bc60952da831aec8736123eb42970c467e5306f30') THEN 1 ELSE 0 END AS checksum_guard;
SELECT 1 / CASE WHEN EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version='20260927_marketing_foundation_v1' AND checksum='sha256:2c09d9e94f03ca78cb93d1cc07438fca0e7ad07395e79078570b35a0825395d5') THEN 1 ELSE 0 END AS foundation_guard;
-- checksum-source-begin
CREATE OR REPLACE FUNCTION ccpun_admin.marketing_window(p_key text,p_end date) RETURNS jsonb LANGUAGE plpgsql IMMUTABLE AS $window$
DECLARE s date; e date:=p_end; ps date; pe date;
BEGIN
 CASE p_key WHEN 'rolling_7' THEN s:=e-6; WHEN 'rolling_28' THEN s:=e-27; WHEN 'this_week' THEN s:=date_trunc('week',e::timestamp)::date; WHEN 'last_week' THEN e:=date_trunc('week',e::timestamp)::date-1;s:=e-6; WHEN 'this_month' THEN s:=date_trunc('month',e::timestamp)::date; WHEN 'last_month' THEN e:=date_trunc('month',e::timestamp)::date-1;s:=date_trunc('month',e::timestamp)::date; ELSE RAISE EXCEPTION 'INVALID_MARKETING_WINDOW'; END CASE;
 IF p_key='this_month' THEN ps:=(s-interval '1 month')::date;pe:=least(s-1,ps+(e-s)); ELSIF p_key='this_week' THEN ps:=s-7;pe:=e-7; ELSIF p_key='last_month' THEN pe:=s-1;ps:=date_trunc('month',pe::timestamp)::date; ELSE pe:=s-1;ps:=pe-(e-s); END IF;
 RETURN jsonb_build_object('key',p_key,'currentStart',s,'currentEnd',e,'previousStart',ps,'previousEnd',pe,'calendarPolicy','Monday-start; provider-native dates; common mature cutoff; Equivalent weekdays for current week; MTD equal elapsed days capped to prior month; full months have differing day counts');
END $window$;
DO $constraints$ DECLARE c record; BEGIN
FOR c IN SELECT conname FROM pg_constraint x WHERE x.conrelid='ccpun_admin.local_ai_job'::regclass AND x.contype='c' AND (SELECT array_agg(a.attname ORDER BY a.attname) FROM pg_attribute a WHERE a.attrelid=x.conrelid AND a.attnum=ANY(x.conkey)) IN(ARRAY['task_type']::name[],ARRAY['data_class','task_type']::name[]) LOOP EXECUTE format('ALTER TABLE ccpun_admin.local_ai_job DROP CONSTRAINT %I',c.conname); END LOOP;
END $constraints$;
ALTER TABLE ccpun_admin.local_ai_job ADD CONSTRAINT local_ai_job_task_type_check CHECK(task_type IN('privacy-redaction','line-intent','content-operations','seo-preprocessing','analytics-review','marketing-analysis'));
ALTER TABLE ccpun_admin.local_ai_job ADD CONSTRAINT local_ai_job_task_data_class_check CHECK((task_type IN('privacy-redaction','line-intent') AND data_class='customer-private') OR(task_type IN('content-operations','seo-preprocessing','analytics-review','marketing-analysis') AND data_class='public-safe'));
CREATE OR REPLACE FUNCTION ccpun_admin.admin_save_marketing_action(p jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $save_action$
DECLARE a ccpun_admin.marketing_action;
BEGIN
 IF octet_length(p::text)>12000 OR (p->>'version')::integer<0 THEN RAISE EXCEPTION 'INVALID_MARKETING_ACTION'; END IF;
 IF p->>'id' IS NULL THEN
  IF (p->>'version')::integer<>0 THEN RAISE EXCEPTION 'MARKETING_ACTION_CONFLICT'; END IF;
  INSERT INTO ccpun_admin.marketing_action(asset_id,priority,action_type,description,expected_metric,owner,status,executed_at,measurement_days,notes,hypothesis,confounder_notes) VALUES(p->>'assetId',p->>'priority',p->>'actionType',p->>'description',p->>'expectedMetric',p->>'owner',p->>'status',(p->>'executedAt')::timestamptz,(p->>'measurementDays')::integer,p->>'notes',p->>'hypothesis',p->>'confounderNotes') RETURNING * INTO a;
 ELSE
  UPDATE ccpun_admin.marketing_action SET version=version+1,asset_id=p->>'assetId',priority=p->>'priority',action_type=p->>'actionType',description=p->>'description',expected_metric=p->>'expectedMetric',owner=p->>'owner',status=p->>'status',executed_at=(p->>'executedAt')::timestamptz,measurement_days=(p->>'measurementDays')::integer,notes=p->>'notes',hypothesis=p->>'hypothesis',confounder_notes=p->>'confounderNotes',updated_at=now() WHERE action_id=(p->>'id')::uuid AND version=(p->>'version')::integer AND (executed_at IS NULL OR (executed_at IS NOT DISTINCT FROM (p->>'executedAt')::timestamptz AND asset_id IS NOT DISTINCT FROM p->>'assetId' AND expected_metric=p->>'expectedMetric' AND measurement_days=(p->>'measurementDays')::integer)) RETURNING * INTO a;
  IF NOT FOUND THEN RAISE EXCEPTION 'MARKETING_ACTION_CONFLICT'; END IF;
 END IF;
 IF a.executed_at IS NOT NULL AND NOT a.baseline_covered AND a.asset_id IS NOT NULL AND a.expected_metric<>'social_views' AND least((now() AT TIME ZONE 'America/Los_Angeles')::date-3,(now() AT TIME ZONE ccpun_admin.admin_marketing_calendar('ga4'))::date-1)>=(a.executed_at AT TIME ZONE 'Asia/Bangkok')::date-1 AND ccpun_admin.marketing_coverage(CASE a.expected_metric WHEN 'organic_sessions' THEN 'ga4-daily-organic' WHEN 'search_clicks' THEN 'gsc-daily-page' ELSE 'ga4-content-events' END,(a.executed_at AT TIME ZONE 'Asia/Bangkok')::date-a.measurement_days,(a.executed_at AT TIME ZONE 'Asia/Bangkok')::date-1) THEN
  UPDATE ccpun_admin.marketing_action SET baseline_value=(SELECT coalesce(sum(d.value),0) FROM ccpun_admin.marketing_daily_metric d WHERE d.metric=a.expected_metric AND d.day BETWEEN (a.executed_at AT TIME ZONE 'Asia/Bangkok')::date-a.measurement_days AND (a.executed_at AT TIME ZONE 'Asia/Bangkok')::date-1 AND EXISTS(SELECT 1 FROM ccpun_admin.marketing_asset_alias al WHERE al.asset_id=a.asset_id AND al.url=ccpun_admin.marketing_canonical_url(d.asset_url))),baseline_covered=a.asset_id IS NOT NULL AND a.expected_metric<>'social_views' AND ccpun_admin.marketing_coverage(CASE a.expected_metric WHEN 'organic_sessions' THEN 'ga4-daily-organic' WHEN 'search_clicks' THEN 'gsc-daily-page' ELSE 'ga4-content-events' END,(a.executed_at AT TIME ZONE 'Asia/Bangkok')::date-a.measurement_days,(a.executed_at AT TIME ZONE 'Asia/Bangkok')::date-1),baseline_manifest=(SELECT coalesce(jsonb_agg(jsonb_build_object('batchId',batch_id,'report',report,'rawHash',raw_sha256)),'[]') FROM ccpun_admin.marketing_report_manifest WHERE period_start<=(a.executed_at AT TIME ZONE 'Asia/Bangkok')::date-1 AND period_end>=(a.executed_at AT TIME ZONE 'Asia/Bangkok')::date-a.measurement_days) WHERE action_id=a.action_id RETURNING * INTO a;
 END IF;
 INSERT INTO ccpun_admin.marketing_action_revision VALUES(a.action_id,a.version,to_jsonb(a),now());
 RETURN ccpun_admin.marketing_action_json(a);
END $save_action$;
CREATE TABLE ccpun_admin.marketing_action_baseline_pin(action_id uuid PRIMARY KEY REFERENCES ccpun_admin.marketing_action(action_id),captured_at timestamptz NOT NULL DEFAULT now(),original_attempt jsonb NOT NULL,final_baseline jsonb NOT NULL);
CREATE TABLE ccpun_admin.marketing_action_measurement(action_id uuid PRIMARY KEY REFERENCES ccpun_admin.marketing_action(action_id),captured_at timestamptz NOT NULL DEFAULT now(),definition_version text NOT NULL CHECK(definition_version='marketing-measurement-v2'),observation jsonb NOT NULL,source_manifest jsonb NOT NULL);
CREATE OR REPLACE FUNCTION ccpun_admin.marketing_action_observation_v2(a ccpun_admin.marketing_action) RETURNS jsonb LANGUAGE sql STABLE SET search_path=pg_catalog,ccpun_admin AS $action_json$
 WITH periods AS(SELECT (a.executed_at AT TIME ZONE 'Asia/Bangkok')::date e),vals AS(SELECT a.baseline_value baseline,sum(value) FILTER(WHERE day BETWEEN e+1 AND e+a.measurement_days) result FROM ccpun_admin.marketing_daily_metric d CROSS JOIN periods WHERE d.metric=a.expected_metric AND EXISTS(SELECT 1 FROM ccpun_admin.marketing_asset_alias al WHERE al.asset_id=a.asset_id AND al.url=ccpun_admin.marketing_canonical_url(d.asset_url))),checks AS(SELECT a.baseline_covered AND a.executed_at IS NOT NULL AND least((now() AT TIME ZONE 'America/Los_Angeles')::date-3,(now() AT TIME ZONE ccpun_admin.admin_marketing_calendar('ga4'))::date-1)>=e+a.measurement_days AND ccpun_admin.marketing_coverage(CASE a.expected_metric WHEN 'organic_sessions' THEN 'ga4-daily-organic' WHEN 'search_clicks' THEN 'gsc-daily-page' ELSE 'ga4-content-events' END,e-a.measurement_days,e+a.measurement_days) ready FROM periods)
 SELECT jsonb_build_object('id',a.action_id,'version',a.version,'assetId',a.asset_id,'priority',a.priority,'actionType',a.action_type,'description',a.description,'expectedMetric',a.expected_metric,'owner',a.owner,'status',a.status,'createdAt',a.created_at,'updatedAt',a.updated_at,'executedAt',a.executed_at,'measurementDays',a.measurement_days,'notes',a.notes,'hypothesis',a.hypothesis,'confounderNotes',a.confounder_notes,'baseline',CASE WHEN ready THEN baseline ELSE NULL END,'result',CASE WHEN ready THEN coalesce(result,0) ELSE NULL END,'absoluteChange',CASE WHEN ready THEN coalesce(result,0)-baseline ELSE NULL END,'percentageChange',CASE WHEN ready AND baseline>0 THEN round((coalesce(result,0)-baseline)*100/baseline,2) ELSE NULL END,'outcome',CASE WHEN NOT ready OR baseline IS NULL  OR baseline=0 THEN 'inconclusive' WHEN coalesce(result,0)>baseline THEN 'improved_after' WHEN coalesce(result,0)<baseline THEN 'declined_after' ELSE 'inconclusive' END,'measurementStatus',CASE WHEN ready THEN 'covered_pre_post_observation_not_causality' ELSE 'awaiting_mature_complete_history' END) FROM vals CROSS JOIN checks
$action_json$;
CREATE OR REPLACE FUNCTION ccpun_admin.marketing_action_json(a ccpun_admin.marketing_action) RETURNS jsonb LANGUAGE sql STABLE SET search_path=pg_catalog,ccpun_admin AS $action$ SELECT ccpun_admin.marketing_action_observation_v2(a)||coalesce((SELECT observation FROM ccpun_admin.marketing_action_measurement WHERE action_id=a.action_id),jsonb_build_object('baseline',NULL,'result',NULL,'absoluteChange',NULL,'percentageChange',NULL,'outcome','inconclusive','measurementStatus','awaiting_mature_complete_history_or_capture')) $action$;
CREATE FUNCTION ccpun_admin.admin_capture_marketing_measurements() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $measure$ DECLARE n integer;candidate ccpun_admin.marketing_action;old jsonb;BEGIN
FOR candidate IN SELECT * FROM ccpun_admin.marketing_action WHERE executed_at IS NOT NULL AND NOT baseline_covered AND asset_id IS NOT NULL AND expected_metric<>'social_views' FOR UPDATE LOOP
IF least((now() AT TIME ZONE 'America/Los_Angeles')::date-3,(now() AT TIME ZONE ccpun_admin.admin_marketing_calendar('ga4'))::date-1)>=(candidate.executed_at AT TIME ZONE 'Asia/Bangkok')::date-1 AND ccpun_admin.marketing_coverage(CASE candidate.expected_metric WHEN 'organic_sessions' THEN 'ga4-daily-organic' WHEN 'search_clicks' THEN 'gsc-daily-page' ELSE 'ga4-content-events' END,(candidate.executed_at AT TIME ZONE 'Asia/Bangkok')::date-candidate.measurement_days,(candidate.executed_at AT TIME ZONE 'Asia/Bangkok')::date-1) THEN
old:=jsonb_build_object('value',candidate.baseline_value,'covered',candidate.baseline_covered,'manifest',candidate.baseline_manifest);
UPDATE ccpun_admin.marketing_action SET baseline_value=(SELECT coalesce(sum(d.value),0) FROM ccpun_admin.marketing_daily_metric d WHERE d.metric=candidate.expected_metric AND d.day BETWEEN (candidate.executed_at AT TIME ZONE 'Asia/Bangkok')::date-candidate.measurement_days AND (candidate.executed_at AT TIME ZONE 'Asia/Bangkok')::date-1 AND EXISTS(SELECT 1 FROM ccpun_admin.marketing_asset_alias al WHERE al.asset_id=candidate.asset_id AND al.url=ccpun_admin.marketing_canonical_url(d.asset_url))),baseline_covered=true,baseline_manifest=(SELECT coalesce(jsonb_agg(jsonb_build_object('batchId',batch_id,'report',report,'rawHash',raw_sha256)),'[]') FROM ccpun_admin.marketing_report_manifest WHERE complete AND period_start<=(candidate.executed_at AT TIME ZONE 'Asia/Bangkok')::date-1 AND period_end>=(candidate.executed_at AT TIME ZONE 'Asia/Bangkok')::date-candidate.measurement_days) WHERE action_id=candidate.action_id RETURNING * INTO candidate;
INSERT INTO ccpun_admin.marketing_action_baseline_pin(action_id,original_attempt,final_baseline) VALUES(candidate.action_id,old,jsonb_build_object('value',candidate.baseline_value,'covered',candidate.baseline_covered,'manifest',candidate.baseline_manifest)) ON CONFLICT(action_id) DO NOTHING;
END IF;END LOOP;
INSERT INTO ccpun_admin.marketing_action_measurement(action_id,definition_version,observation,source_manifest)
SELECT a.action_id,'marketing-measurement-v2',jsonb_build_object('baseline',o->'baseline','result',o->'result','absoluteChange',o->'absoluteChange','percentageChange',o->'percentageChange','outcome',o->'outcome','measurementStatus',o->'measurementStatus'),coalesce((SELECT jsonb_agg(jsonb_build_object('batchId',m.batch_id,'report',m.report,'rawHash',m.raw_sha256,'collectedAt',m.collected_at,'periodStart',m.period_start,'periodEnd',m.period_end)) FROM ccpun_admin.marketing_report_manifest m WHERE m.complete AND m.period_start<=(a.executed_at AT TIME ZONE 'Asia/Bangkok')::date+a.measurement_days AND m.period_end>=(a.executed_at AT TIME ZONE 'Asia/Bangkok')::date-a.measurement_days),'[]')
FROM ccpun_admin.marketing_action a CROSS JOIN LATERAL(SELECT ccpun_admin.marketing_action_observation_v2(a) o) x WHERE a.executed_at IS NOT NULL AND a.expected_metric<>'social_views' AND o->>'measurementStatus'='covered_pre_post_observation_not_causality' ON CONFLICT(action_id) DO NOTHING;GET DIAGNOSTICS n=ROW_COUNT;RETURN jsonb_build_object('status','ready','captured',n,'method','equal mature pre/post observational windows; no causality');END $measure$;
REVOKE ALL ON ccpun_admin.marketing_action_baseline_pin,ccpun_admin.marketing_action_measurement FROM PUBLIC,ccpun_admin_runtime,ccpun_local_ai_runtime;
REVOKE ALL ON FUNCTION ccpun_admin.marketing_action_observation_v2(ccpun_admin.marketing_action),ccpun_admin.admin_capture_marketing_measurements() FROM PUBLIC,ccpun_admin_runtime,ccpun_local_ai_runtime;
GRANT EXECUTE ON FUNCTION ccpun_admin.admin_capture_marketing_measurements() TO ccpun_admin_runtime;
CREATE TABLE ccpun_admin.marketing_analysis(analysis_id uuid PRIMARY KEY,input_hash text NOT NULL UNIQUE CHECK(input_hash~'^[a-f0-9]{64}$'),input_json jsonb NOT NULL CHECK(octet_length(input_json::text)<=24000),source_manifest jsonb NOT NULL CHECK(jsonb_typeof(source_manifest)='array'),prompt_version text NOT NULL CHECK(prompt_version='marketing-performance-v1'),window_key text NOT NULL,analysis_type text NOT NULL,period_start date NOT NULL,period_end date NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),job_id uuid UNIQUE REFERENCES ccpun_admin.local_ai_job(job_id),validation_status text NOT NULL DEFAULT 'pending' CHECK(validation_status IN('pending','validated','rejected')),output_json jsonb,validated_at timestamptz,output_digest text);
CREATE INDEX marketing_analysis_window ON ccpun_admin.marketing_analysis(window_key,created_at DESC);
CREATE FUNCTION ccpun_admin.admin_prepare_marketing_analysis(p_id uuid,p_input jsonb,p_hash text,p_manifest jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $prepare$
DECLARE a ccpun_admin.marketing_analysis; BEGIN
IF p_hash!~'^[a-f0-9]{64}$' OR p_input->>'promptVersion'<>'marketing-performance-v1' OR jsonb_typeof(p_input->'evidence')<>'array' OR jsonb_array_length(p_input->'evidence') NOT BETWEEN 1 AND 16 OR octet_length(p_input::text)>24000 OR jsonb_typeof(p_manifest)<>'array' OR octet_length(p_manifest::text)>4000000 THEN RAISE EXCEPTION 'MARKETING_INPUT_INVALID'; END IF;
PERFORM pg_advisory_xact_lock(hashtext('marketing-prepare:'||p_hash));SELECT * INTO a FROM ccpun_admin.marketing_analysis WHERE input_hash=p_hash;
IF FOUND THEN RETURN jsonb_build_object('analysisId',a.analysis_id,'inputHash',a.input_hash,'status','prepared','reused',true,'coverage',a.input_json->'coverage'); END IF;
INSERT INTO ccpun_admin.marketing_analysis(analysis_id,input_hash,input_json,source_manifest,prompt_version,window_key,analysis_type,period_start,period_end) VALUES(p_id,p_hash,p_input,p_manifest,p_input->>'promptVersion',p_input#>>'{period,key}',p_input->>'analysisType',(p_input#>>'{period,currentStart}')::date,(p_input#>>'{period,currentEnd}')::date);
RETURN jsonb_build_object('analysisId',p_id,'inputHash',p_hash,'status','prepared','reused',false,'coverage',p_input->'coverage');END $prepare$;
CREATE FUNCTION ccpun_admin.admin_marketing_analysis_input(p_id uuid,p_hash text) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $input$ SELECT input_json FROM ccpun_admin.marketing_analysis WHERE analysis_id=p_id AND input_hash=p_hash $input$;
CREATE FUNCTION ccpun_admin.admin_enqueue_marketing_analysis(p_id uuid,p_job uuid,p_cipher text,p_nonce text,p_tag text,p_key smallint,p_hash text,p_actor text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $enqueue$
DECLARE a ccpun_admin.marketing_analysis;r record;BEGIN
SELECT * INTO a FROM ccpun_admin.marketing_analysis WHERE analysis_id=p_id AND input_hash=p_hash FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'MARKETING_ANALYSIS_IDENTITY_INVALID';END IF;
IF a.job_id IS NOT NULL THEN RETURN ccpun_admin.admin_marketing_analysis_status(p_id)||jsonb_build_object('reused',true);END IF;
IF NOT EXISTS(SELECT 1 FROM ccpun_admin.local_ai_worker_heartbeat h WHERE h.last_seen_at>now()-interval '90 seconds' AND h.ollama_ready AND NOT h.accepting_private_jobs AND h.model_name='qwen3:1.7b' AND h.details_json->>'marketingAnalysisVersion'='marketing-performance-v1') OR EXISTS(SELECT 1 FROM ccpun_admin.local_ai_worker_heartbeat h WHERE h.last_seen_at>now()-interval '90 seconds' AND h.details_json->>'marketingAnalysisVersion' IS DISTINCT FROM 'marketing-performance-v1') THEN RAISE EXCEPTION 'MARKETING_WORKER_NOT_READY';END IF;
SELECT * INTO r FROM ccpun_admin.admin_enqueue_local_ai_job_v2(p_job,'marketing-analysis','public-safe',p_cipher,p_nonce,p_tag,p_key,encode(sha256(convert_to('marketing-analysis:'||p_hash,'UTF8')),'hex'),p_hash,p_actor,'batch');
IF r.outcome NOT IN('inserted','reused') THEN RETURN jsonb_build_object('analysisId',p_id,'status','prepared','outcome',r.outcome,'reused',false);END IF;
UPDATE ccpun_admin.marketing_analysis SET job_id=r.job_id WHERE analysis_id=p_id;
RETURN jsonb_build_object('analysisId',p_id,'jobId',r.job_id,'status','queued','reused',r.reused);END $enqueue$;
CREATE FUNCTION ccpun_admin.admin_marketing_analysis_status(p_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $status$
SELECT jsonb_build_object('analysisId',a.analysis_id,'jobId',a.job_id,'status',CASE WHEN a.validation_status='validated' AND a.period_end<(ccpun_admin.marketing_window(a.window_key,least((now() AT TIME ZONE 'America/Los_Angeles')::date-3,(now() AT TIME ZONE 'Asia/Bangkok')::date-1))->>'currentEnd')::date THEN 'stale' WHEN a.validation_status='validated' THEN 'ready' WHEN j.status='leased' THEN 'running' WHEN a.validation_status='rejected' OR j.status IN('failed','cancelled','expired','reconciliation-required') THEN 'failed' WHEN a.job_id IS NULL THEN 'prepared' ELSE 'queued' END,'workerSucceeded',coalesce(j.status='succeeded',false)) FROM ccpun_admin.marketing_analysis a LEFT JOIN ccpun_admin.local_ai_job j USING(job_id) WHERE a.analysis_id=p_id $status$;
CREATE FUNCTION ccpun_admin.admin_marketing_analysis_validation_input(p_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $validation$ SELECT jsonb_build_object('input',a.input_json,'output',j.output_json,'outputDigest',j.output_digest) FROM ccpun_admin.marketing_analysis a JOIN ccpun_admin.local_ai_job j USING(job_id) WHERE a.analysis_id=p_id AND j.task_type='marketing-analysis' AND j.data_class='public-safe' AND j.status='succeeded' AND j.review_status IN('pending','approved') AND j.output_json IS NOT NULL $validation$;
CREATE FUNCTION ccpun_admin.admin_validate_marketing_analysis(p_id uuid,p_digest text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $validate$ DECLARE a ccpun_admin.marketing_analysis;j ccpun_admin.local_ai_job;BEGIN
SELECT * INTO a FROM ccpun_admin.marketing_analysis WHERE analysis_id=p_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'MARKETING_ANALYSIS_UNKNOWN';END IF;SELECT * INTO j FROM ccpun_admin.local_ai_job WHERE job_id=a.job_id;
IF j.task_type IS DISTINCT FROM 'marketing-analysis' OR j.data_class IS DISTINCT FROM 'public-safe' OR j.status IS DISTINCT FROM 'succeeded' OR j.review_status NOT IN('pending','approved') OR j.output_digest IS DISTINCT FROM p_digest OR j.output_json->>'snapshotHash' IS DISTINCT FROM a.input_json->>'snapshotHash' OR j.output_json->>'sourceManifestHash' IS DISTINCT FROM a.input_json->>'sourceManifestHash' THEN RAISE EXCEPTION 'MARKETING_OUTPUT_CONCURRENT_CHANGE';END IF;
UPDATE ccpun_admin.marketing_analysis SET validation_status='validated',output_json=j.output_json,validated_at=coalesce(validated_at,now()),output_digest=p_digest WHERE analysis_id=p_id;
RETURN jsonb_build_object('analysisId',p_id,'status','ready','validated',true);END $validate$;
CREATE FUNCTION ccpun_admin.admin_reject_marketing_analysis(p_id uuid,p_digest text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $reject$ BEGIN UPDATE ccpun_admin.marketing_analysis a SET validation_status='rejected' FROM ccpun_admin.local_ai_job j WHERE a.analysis_id=p_id AND j.job_id=a.job_id AND a.validation_status<>'validated' AND j.status='succeeded' AND j.output_digest=p_digest;RETURN jsonb_build_object('analysisId',p_id,'status','failed','validationError','grounding-rejected');END $reject$;
CREATE FUNCTION ccpun_admin.marketing_analysis_json(a ccpun_admin.marketing_analysis) RETURNS jsonb LANGUAGE sql STABLE SET search_path=pg_catalog,ccpun_admin AS $shape$
SELECT jsonb_build_object('analysisId',a.analysis_id,'jobId',a.job_id,'status',CASE WHEN a.validation_status='validated' AND a.period_end<(ccpun_admin.marketing_window(a.window_key,least((now() AT TIME ZONE 'America/Los_Angeles')::date-3,(now() AT TIME ZONE 'Asia/Bangkok')::date-1))->>'currentEnd')::date THEN 'stale' WHEN a.validation_status='validated' THEN 'ready' WHEN j.status='leased' THEN 'running' WHEN a.validation_status='rejected' OR j.status IN('failed','cancelled','expired','reconciliation-required') THEN 'failed' WHEN a.job_id IS NULL THEN 'prepared' ELSE 'queued' END,'promptVersion',a.prompt_version,'analysisType',a.analysis_type,'period',a.input_json->'period','createdAt',a.created_at,'completedAt',a.validated_at,'modelName',j.model_name,'inputHash',a.input_hash,'sourceManifest',a.source_manifest,'output',CASE WHEN a.validation_status='validated' AND j.review_status IN('pending','approved') THEN a.output_json END) FROM(SELECT 1) x LEFT JOIN ccpun_admin.local_ai_job j ON j.job_id=a.job_id $shape$;
CREATE FUNCTION ccpun_admin.admin_read_marketing_analysis(p_window text) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $read$ SELECT jsonb_build_object('latest',(SELECT ccpun_admin.marketing_analysis_json(a) FROM ccpun_admin.marketing_analysis a WHERE a.window_key=p_window ORDER BY a.created_at DESC LIMIT 1),'lastGood',(SELECT ccpun_admin.marketing_analysis_json(a) FROM ccpun_admin.marketing_analysis a JOIN ccpun_admin.local_ai_job j USING(job_id) WHERE a.window_key=p_window AND a.validation_status='validated' AND j.review_status IN('pending','approved') ORDER BY a.validated_at DESC LIMIT 1)) $read$;
CREATE OR REPLACE FUNCTION ccpun_admin.marketing_coverage(p_report text,p_start date,p_end date) RETURNS boolean LANGUAGE sql STABLE SET search_path=pg_catalog,ccpun_admin AS $coverage$
 SELECT p_end>=p_start AND NOT EXISTS(SELECT 1 FROM generate_series(p_start,p_end,interval '1 day') d WHERE NOT EXISTS(SELECT 1 FROM ccpun_admin.marketing_report_manifest m JOIN ccpun_admin.analytics_daily_batch b USING(batch_id) WHERE m.report=p_report AND m.complete AND b.status='completed' AND m.resource_scope<>'legacy-unverified' AND d::date BETWEEN m.period_start AND m.period_end))
$coverage$;
CREATE FUNCTION ccpun_admin.marketing_window_calendar(p_key text,p_end date,p_calendar date) RETURNS jsonb LANGUAGE plpgsql IMMUTABLE AS $cal$ DECLARE w jsonb;s date;e date;ps date;pe date;BEGIN
IF p_key IN('rolling_7','rolling_28') THEN RETURN ccpun_admin.marketing_window(p_key,p_end)||jsonb_build_object('availability','mature_data');END IF;
CASE p_key WHEN 'this_week' THEN s:=date_trunc('week',p_calendar::timestamp)::date;e:=p_end;ps:=s-7;pe:=e-7;
WHEN 'last_week' THEN s:=date_trunc('week',p_calendar::timestamp)::date-7;e:=least(s+6,p_end);ps:=s-7;pe:=e-7;
WHEN 'this_month' THEN s:=date_trunc('month',p_calendar::timestamp)::date;e:=p_end;ps:=(s-interval '1 month')::date;pe:=least(s-1,ps+(e-s));
WHEN 'last_month' THEN s:=(date_trunc('month',p_calendar::timestamp)-interval '1 month')::date;e:=least((date_trunc('month',p_calendar::timestamp))::date-1,p_end);ps:=(s-interval '1 month')::date;pe:=CASE WHEN e=date_trunc('month',p_calendar::timestamp)::date-1 THEN s-1 ELSE least(s-1,ps+(e-s)) END;
ELSE RAISE EXCEPTION 'INVALID_MARKETING_WINDOW';END CASE;
RETURN jsonb_build_object('key',p_key,'currentStart',s,'currentEnd',e,'previousStart',ps,'previousEnd',pe,'availability',CASE WHEN e<s THEN 'no_mature_data' ELSE 'mature_data' END,'calendarPolicy','Business calendar Asia/Bangkok; mature provider cutoff; equivalent weekdays; partial month elapsed days capped to prior month; full-month day counts may differ');END $cal$;
CREATE OR REPLACE FUNCTION ccpun_admin.marketing_read_core_v2(p_key text DEFAULT 'rolling_7',p_now timestamptz DEFAULT now()) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $read$
DECLARE w jsonb; cs date;ce date;ps date;pe date;board jsonb;boards jsonb:='[]';kpis jsonb;health jsonb;manifest jsonb;actions jsonb;opportunities jsonb;rule record;content jsonb;extra jsonb;
BEGIN
 IF EXISTS(SELECT 1 FROM ccpun_admin.marketing_report_manifest m JOIN ccpun_admin.analytics_daily_batch b USING(batch_id) WHERE b.status='completed' AND m.collected_at>p_now) THEN RAISE EXCEPTION 'MARKETING_CUTOFF_SUPERSEDED'; END IF;
 -- One common mature cutoff; dates remain native provider dates, not relabelled time instants.
 w:=ccpun_admin.marketing_window_calendar(p_key,least((p_now AT TIME ZONE 'America/Los_Angeles')::date-3,(p_now AT TIME ZONE ccpun_admin.admin_marketing_calendar('ga4'))::date-1),(p_now AT TIME ZONE 'Asia/Bangkok')::date);cs:=(w->>'currentStart')::date;ce:=(w->>'currentEnd')::date;ps:=(w->>'previousStart')::date;pe:=(w->>'previousEnd')::date;
 SELECT coalesce(jsonb_agg(ccpun_admin.marketing_metric_record(r.metric,(SELECT sum(value) FROM ccpun_admin.marketing_daily_metric WHERE metric=r.metric AND day BETWEEN cs AND ce),(SELECT sum(value) FROM ccpun_admin.marketing_daily_metric WHERE metric=r.metric AND day BETWEEN ps AND pe),ccpun_admin.marketing_coverage(CASE WHEN r.metric='organic_sessions' THEN 'ga4-daily-organic' WHEN r.metric LIKE 'search_%' THEN 'gsc-daily-page' ELSE 'ga4-content-events' END,cs,ce),ccpun_admin.marketing_coverage(CASE WHEN r.metric='organic_sessions' THEN 'ga4-daily-organic' WHEN r.metric LIKE 'search_%' THEN 'gsc-daily-page' ELSE 'ga4-content-events' END,ps,pe),'kpi:'||r.metric) ORDER BY r.metric),'[]') INTO kpis FROM ccpun_admin.marketing_metric_rule r WHERE r.metric IN('organic_sessions','search_clicks','search_impressions','line_clicks','calculator_complete');
 FOR rule IN SELECT * FROM ccpun_admin.marketing_metric_rule WHERE metric IN('organic_sessions','search_clicks','line_clicks','calculator_complete') LOOP
  WITH totals AS(SELECT ccpun_admin.marketing_canonical_url(asset_url) url,sum(value) FILTER(WHERE day BETWEEN cs AND ce) current,sum(value) FILTER(WHERE day BETWEEN ps AND pe) previous FROM ccpun_admin.marketing_daily_metric WHERE metric=rule.metric AND day BETWEEN ps AND ce GROUP BY 1), ranked AS(SELECT t.*,a.asset_id,a.title,a.category,a.published_at,row_number() OVER(ORDER BY t.current DESC NULLS LAST,t.url) rank FROM totals t LEFT JOIN ccpun_admin.marketing_asset_alias al ON al.url=t.url LEFT JOIN ccpun_admin.marketing_asset a USING(asset_id) WHERE t.current IS NOT NULL AND t.url IS NOT NULL)
  SELECT coalesce(jsonb_agg(ccpun_admin.marketing_metric_record(rule.metric,current,previous,ccpun_admin.marketing_coverage(CASE WHEN rule.metric='organic_sessions' THEN 'ga4-daily-organic' WHEN rule.metric='search_clicks' THEN 'gsc-daily-page' ELSE 'ga4-content-events' END,cs,ce),ccpun_admin.marketing_coverage(CASE WHEN rule.metric='organic_sessions' THEN 'ga4-daily-organic' WHEN rule.metric='search_clicks' THEN 'gsc-daily-page' ELSE 'ga4-content-events' END,ps,pe),'content:'||rule.metric||':'||coalesce(asset_id,url))||jsonb_build_object('rank',rank,'assetId',coalesce(asset_id,'unmapped:'||url),'title',coalesce(title,url),'url',url,'category',category,'publishedAt',published_at,'mappingStatus',CASE WHEN asset_id IS NULL THEN 'unmapped' ELSE 'mapped' END,'lifecycle',CASE WHEN published_at::date>=cs-28 THEN 'new' ELSE 'insufficient_history' END) ORDER BY rank),'[]') INTO board FROM ranked WHERE rank<=10;
  boards:=boards||jsonb_build_array(jsonb_build_object('id',rule.metric,'title',CASE rule.metric WHEN 'organic_sessions' THEN 'Top Organic Content' WHEN 'search_clicks' THEN 'Top Search Content' WHEN 'line_clicks' THEN 'Top LINE Intent Activity' ELSE 'Top Calculator Completion Activity' END,'metric',rule.metric,'basis',rule.metric||' descending; URL tie-break; provider-native daily facts; event counts are repeatable','platform',NULL,'rows',board));
 END LOOP;
 -- Social: native snapshot values for posts published in period, never weekly Reach/activity deltas.
 FOR rule IN SELECT unnest(ARRAY['Facebook','Instagram']) AS metric LOOP
  WITH latest AS(SELECT DISTINCT ON(platform,object_id) * FROM ccpun_admin.marketing_social_unified s WHERE captured_at<=p_now ORDER BY platform,object_id,captured_at DESC),ranked AS(SELECT *,row_number() OVER(ORDER BY views DESC,object_id) rank FROM latest WHERE platform=rule.metric AND published_at::date BETWEEN cs AND ce AND views IS NOT NULL)
  SELECT coalesce(jsonb_agg(ccpun_admin.marketing_metric_record('social_views',views,NULL,true,false,'social:'||platform||':'||object_id)||jsonb_build_object('rank',rank,'assetId','social:'||platform||':'||object_id,'title',object_id,'url',url,'category',content_type,'publishedAt',published_at,'mappingStatus','unmapped','lifecycle','new') ORDER BY rank),'[]') INTO board FROM ranked WHERE rank<=10;
  boards:=boards||jsonb_build_array(jsonb_build_object('id','social_'||lower(rule.metric),'title','Top '||rule.metric||' published posts · snapshot views','metric','social_views','basis','Posts published in selected period, ranked by latest native cumulative views; NOT activity during period','platform',rule.metric,'rows',board));
 END LOOP;
 WITH latest AS(SELECT DISTINCT ON(report) m.* FROM ccpun_admin.marketing_report_manifest m JOIN ccpun_admin.analytics_daily_batch b USING(batch_id) WHERE b.status='completed' AND m.collected_at<=p_now ORDER BY report,m.collected_at DESC),attempt AS(SELECT DISTINCT ON(source) source,status,error_category,attempted_at FROM ccpun_admin.analytics_daily_batch WHERE attempted_at<=p_now ORDER BY source,attempted_at DESC)
 SELECT coalesce(jsonb_agg(jsonb_build_object('source',b.source,'report',m.report,'sourceAsOf',m.source_as_of,'collectedAt',m.collected_at,'lastSuccess',m.collected_at,'lastError',a.error_category,'expectedLagDays',CASE b.source WHEN 'gsc' THEN 3 ELSE 1 END,'status',CASE WHEN a.status='failed' THEN 'failed' WHEN m.source_as_of IS NULL THEN 'unknown' WHEN (p_now AT TIME ZONE 'Asia/Bangkok')::date-m.source_as_of_date>CASE b.source WHEN 'gsc' THEN 5 ELSE 3 END THEN 'stale' WHEN b.source='gsc' THEN 'expected_lag' ELSE 'fresh' END,'coverageStart',m.period_start,'coverageEnd',m.period_end,'timezone',m.source_timezone,'limitations',m.limitations) ORDER BY m.report),'[]') INTO health FROM latest m JOIN ccpun_admin.analytics_daily_batch b USING(batch_id) LEFT JOIN attempt a USING(source);
 SELECT coalesce(jsonb_agg(jsonb_build_object('batchId',batch_id,'report',report,'rawHash',raw_sha256,'periodStart',period_start,'periodEnd',period_end,'sourceAsOf',source_as_of,'collectedAt',collected_at,'timezone',source_timezone,'limitations',limitations)),'[]') INTO manifest FROM ccpun_admin.marketing_report_manifest WHERE collected_at<=p_now AND ((period_start<=ce AND period_end>=ps) OR period_start IS NULL);
 content:=ccpun_admin.marketing_content_metrics(cs,ce,ps,pe);
 WITH latest AS(SELECT DISTINCT ON(platform,object_id) * FROM ccpun_admin.marketing_social_unified WHERE captured_at<=p_now ORDER BY platform,object_id,captured_at DESC),assets AS(SELECT * FROM latest ORDER BY platform,object_id LIMIT 2000)
 SELECT coalesce(jsonb_agg(jsonb_build_object('assetId','social:'||platform||':'||object_id,'title',object_id,'url',coalesce(url,''),'category',content_type,'topic',NULL,'publishedAt',published_at,'mappingStatus','unmapped','lifecycle',CASE WHEN published_at::date>=cs-28 THEN 'new' ELSE 'insufficient_history' END,'metrics',(SELECT jsonb_agg(ccpun_admin.marketing_metric_record(metric,value,NULL,false,false,'social:'||platform||':'||object_id||':'||metric)||jsonb_build_object('freshnessStatus',CASE WHEN captured_at>=p_now-interval '3 days' THEN 'fresh' ELSE 'stale' END,'coverageStatus','native_snapshot_not_period_activity','unit',CASE WHEN metric='social_reach' THEN 'native_reach' ELSE 'native_counter' END)) FROM (VALUES('social_views',views),('social_reach',reach),('social_interactions',interactions),('social_shares',shares),('social_saves',saves)) m(metric,value))) ORDER BY platform,object_id),'[]') INTO extra FROM assets;
 content:=content||extra;
 FOR rule IN SELECT unnest(ARRAY['growing','declining','new','evergreen']) AS metric LOOP
  WITH rows AS(SELECT c,(SELECT m FROM jsonb_array_elements(c->'metrics') m WHERE m->>'metric'='organic_sessions') m FROM jsonb_array_elements(content) c),ranked AS(SELECT *,row_number() OVER(ORDER BY CASE WHEN rule.metric='growing' THEN (m->>'absoluteChange')::numeric WHEN rule.metric='declining' THEN -(m->>'absoluteChange')::numeric ELSE (m->>'current')::numeric END DESC,c->>'assetId') rank FROM rows WHERE m IS NOT NULL AND CASE WHEN rule.metric='new' THEN c->>'lifecycle'='new' WHEN rule.metric='evergreen' THEN c->>'lifecycle'='evergreen' WHEN rule.metric='growing' THEN m->>'sampleStatus'='sufficient' AND (m->>'percentageChange')::numeric>=25 WHEN rule.metric='declining' THEN m->>'sampleStatus'='sufficient' AND (m->>'percentageChange')::numeric<=-25 ELSE false END) SELECT coalesce(jsonb_agg(m||jsonb_build_object('rank',rank,'assetId',c->>'assetId','url',c->>'url','title',c->>'title','category',c->>'category','publishedAt',c->>'publishedAt','mappingStatus',c->>'mappingStatus','lifecycle',c->>'lifecycle') ORDER BY rank),'[]') INTO extra FROM ranked WHERE rank<=10;
  boards:=boards||jsonb_build_array(jsonb_build_object('id',rule.metric,'title','Top '||rule.metric||' organic content','metric','organic_sessions','basis',CASE WHEN rule.metric IN('growing','declining') THEN 'Valid comparable period change after minimum-volume threshold; absolute change ranking' ELSE 'Organic sessions; new/lifecycle eligibility from versioned deterministic rules' END,'platform',NULL,'rows',extra));
 END LOOP;
 SELECT coalesce(jsonb_agg(ccpun_admin.marketing_action_json(a.*) ORDER BY a.updated_at DESC),'[]') INTO actions FROM(SELECT * FROM ccpun_admin.marketing_action ORDER BY updated_at DESC LIMIT 100) a;
 SELECT coalesce(jsonb_agg(jsonb_build_object('id','decline:'||(x->>'metric'),'area','performance','assetId',NULL,'title','Investigate material decline: '||(x->>'metric'),'priority','high','evidenceRefs',jsonb_build_array(x->>'evidenceRef'),'recommendedAction','investigation','confidence','medium','reason','Comparable covered periods exceed minimum volumes; decline is an observation, not a causal conclusion')),'[]') INTO opportunities FROM jsonb_array_elements(kpis) x JOIN ccpun_admin.marketing_metric_rule r ON r.metric=x->>'metric' WHERE x->>'sampleStatus'='sufficient' AND (x->>'percentageChange')::numeric<=-r.decline_percent;
 SELECT opportunities||coalesce(jsonb_agg(jsonb_build_object('id','health:'||(h->>'report'),'area','data_health','assetId',NULL,'title','Check source freshness: '||(h->>'report'),'priority','medium','evidenceRefs',jsonb_build_array('health:'||(h->>'report')),'recommendedAction','investigation','confidence','low','reason','Source is stale or latest attempt failed; qualify recommendations until current evidence is available')),'[]') INTO opportunities FROM jsonb_array_elements(health) h WHERE h->>'status' IN('stale','failed');
 RETURN jsonb_build_object('state','ready','version','marketing-v1','generatedAt',p_now,'window',w,'kpis',kpis,'contentPerformance',content,'campaigns',(SELECT coalesce(jsonb_agg(jsonb_build_object('sourceMedium',source_medium,'campaign',campaign,'landingUrl',url,'assetId',asset_id,'sessions',sessions,'engagedSessions',engaged,'keyEvents',key_events,'coverageStatus',CASE WHEN ccpun_admin.marketing_coverage('ga4-session-performance',cs,ce) THEN 'complete' ELSE 'partial' END,'periodStart',cs,'periodEnd',ce) ORDER BY sessions DESC,url),'[]') FROM(SELECT f.source_medium,f.campaign,ccpun_admin.marketing_canonical_url(f.landing_page) url,al.asset_id,sum(f.sessions) sessions,sum(f.engaged_sessions) engaged,sum(f.key_events) key_events FROM ccpun_admin.marketing_ga4_current f LEFT JOIN ccpun_admin.marketing_asset_alias al ON al.url=ccpun_admin.marketing_canonical_url(f.landing_page) WHERE f.report='ga4-session-performance' AND f.day BETWEEN cs AND ce GROUP BY 1,2,3,4 ORDER BY sum(f.sessions) DESC LIMIT 2000) c),'benchmarks',(SELECT coalesce(jsonb_agg(jsonb_build_object('positionBand',position_band,'cohortSize',cohort_size,'medianCtr',median_ctr,'definition',definition)),'[]') FROM ccpun_admin.marketing_search_benchmark),'leaderboards',boards,'trend',(SELECT coalesce(jsonb_agg(jsonb_build_object('date',day,'metric',metric,'value',value) ORDER BY day,metric),'[]') FROM(SELECT day,metric,sum(value) value FROM ccpun_admin.marketing_daily_metric WHERE day BETWEEN cs AND ce GROUP BY day,metric) t),'funnel',jsonb_build_object('mode','activity-only','steps',(SELECT coalesce(jsonb_agg(jsonb_build_object('event',event_name,'count',count,'status','repeatable_event_count')),'[]') FROM(SELECT event_name,sum(event_count) count FROM ccpun_admin.marketing_event_current WHERE report='ga4-marketing-events' AND day BETWEEN cs AND ce GROUP BY event_name) e),'limitation','Behavioral events are not confirmed leads; no cohort/session sequence, so conversion/drop-off rates and downstream outcomes are unavailable'),'health',health,'opportunities',opportunities,'actions',actions,'manifest',manifest,'notes',jsonb_build_array('Numerical facts use latest native-key provider revisions; overlapping rolling reports are never summed.','Blank is unavailable; zero requires a successfully covered report window.','GA4 distinct users and native Reach are nonadditive; no summed distinct-user metric is emitted.','North Star qualified conversations, appointments and revenue are unavailable without governed business outcomes.','Growth/decline, evergreen lifecycle and benchmark confidence require sufficient comparable history.','MTD uses equivalent elapsed days; cross-source native-date/timezone alignment is disclosed.','Actions are managed in Admin/Neon; bounded versioned Sheet imports preserve human fields and conflicts.'));
END $read$;
CREATE FUNCTION ccpun_admin.admin_read_marketing_v2(p_key text DEFAULT 'rolling_7',p_now timestamptz DEFAULT now()) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $facts$
DECLARE d jsonb;cs date;ce date;health jsonb;BEGIN
d:=ccpun_admin.marketing_read_core_v2(p_key,p_now);cs:=(d#>>'{window,currentStart}')::date;ce:=(d#>>'{window,currentEnd}')::date;
d:=jsonb_set(d,'{funnel,steps}',(SELECT coalesce(jsonb_agg(jsonb_build_object('event',event_name,'count',count,'status',CASE WHEN ccpun_admin.marketing_coverage('ga4-content-events',cs,ce) THEN 'observed_repeatable_event_count' ELSE 'partial_repeatable_event_count' END) ORDER BY event_name),'[]') FROM(SELECT event_name,sum(event_count) count FROM ccpun_admin.marketing_event_current WHERE report='ga4-content-events' AND day BETWEEN cs AND ce GROUP BY event_name)e));
WITH required(report) AS(VALUES('gsc-daily-page'),('gsc-daily-query-page'),('ga4-daily-organic'),('ga4-content-events')),
latest AS(SELECT DISTINCT ON(m.report) m.*,b.source FROM ccpun_admin.marketing_report_manifest m JOIN ccpun_admin.analytics_daily_batch b USING(batch_id) WHERE m.collected_at<=p_now AND m.complete ORDER BY m.report,m.period_end DESC NULLS LAST,m.collected_at DESC),
attempt AS(SELECT DISTINCT ON(source) source,status,error_category FROM ccpun_admin.analytics_daily_batch WHERE attempted_at<=p_now ORDER BY source,attempted_at DESC)
SELECT coalesce(jsonb_agg(jsonb_build_object('source',coalesce(m.source,CASE WHEN r.report LIKE 'gsc-%' THEN 'gsc' ELSE 'ga4' END),'report',r.report,'sourceAsOf',m.source_as_of,'collectedAt',m.collected_at,'lastSuccess',m.collected_at,'lastError',a.error_category,'expectedLagDays',CASE WHEN r.report LIKE 'gsc-%' THEN 3 ELSE 1 END,'status',CASE WHEN a.status='failed' THEN 'failed' WHEN m.report IS NULL THEN 'unknown' WHEN m.period_end<ce THEN 'stale' WHEN r.report LIKE 'gsc-%' OR m.period_end<(p_now AT TIME ZONE coalesce(m.source_timezone,'America/Los_Angeles'))::date-1 THEN 'expected_lag' ELSE 'fresh' END,'coverageStart',m.period_start,'coverageEnd',m.period_end,'timezone',m.source_timezone,'limitations',coalesce(m.limitations,'[]'::jsonb)||jsonb_build_array('Daily sources align to the common mature cutoff; GA4 native availability may be newer')) ORDER BY r.report),'[]') INTO health FROM required r LEFT JOIN latest m USING(report) LEFT JOIN attempt a ON a.source=coalesce(m.source,CASE WHEN r.report LIKE 'gsc-%' THEN 'gsc' ELSE 'ga4' END);
SELECT health||coalesce(jsonb_agg(h),'[]') INTO health FROM jsonb_array_elements(d->'health') h WHERE h->>'report' NOT IN('gsc-daily-page','gsc-daily-query-page','ga4-daily-organic','ga4-content-events');
RETURN jsonb_set(d,'{health}',health);END $facts$;
REVOKE ALL ON FUNCTION ccpun_admin.marketing_window_calendar(text,date,date),ccpun_admin.marketing_read_core_v2(text,timestamptz) FROM PUBLIC,ccpun_admin_runtime,ccpun_local_ai_runtime;
REVOKE ALL ON ccpun_admin.marketing_analysis FROM PUBLIC,ccpun_admin_runtime,ccpun_local_ai_runtime;
REVOKE ALL ON FUNCTION ccpun_admin.admin_prepare_marketing_analysis(uuid,jsonb,text,jsonb),ccpun_admin.admin_marketing_analysis_input(uuid,text),ccpun_admin.admin_enqueue_marketing_analysis(uuid,uuid,text,text,text,smallint,text,text),ccpun_admin.admin_marketing_analysis_status(uuid),ccpun_admin.admin_marketing_analysis_validation_input(uuid),ccpun_admin.admin_validate_marketing_analysis(uuid,text),ccpun_admin.admin_reject_marketing_analysis(uuid,text),ccpun_admin.marketing_analysis_json(ccpun_admin.marketing_analysis),ccpun_admin.admin_read_marketing_analysis(text),ccpun_admin.admin_read_marketing_v2(text,timestamptz) FROM PUBLIC,ccpun_admin_runtime,ccpun_local_ai_runtime;
GRANT EXECUTE ON FUNCTION ccpun_admin.admin_prepare_marketing_analysis(uuid,jsonb,text,jsonb),ccpun_admin.admin_marketing_analysis_input(uuid,text),ccpun_admin.admin_enqueue_marketing_analysis(uuid,uuid,text,text,text,smallint,text,text),ccpun_admin.admin_marketing_analysis_status(uuid),ccpun_admin.admin_marketing_analysis_validation_input(uuid),ccpun_admin.admin_validate_marketing_analysis(uuid,text),ccpun_admin.admin_reject_marketing_analysis(uuid,text),ccpun_admin.admin_read_marketing_analysis(text),ccpun_admin.admin_read_marketing_v2(text,timestamptz) TO ccpun_admin_runtime;
CREATE OR REPLACE FUNCTION ccpun_admin.admin_read_analytics_daily(p_cutoff timestamptz DEFAULT now())
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $analytics_read$
WITH sources AS (SELECT unnest(ARRAY['gsc','ga4','meta','ubersuggest']) AS source),
attempts AS (SELECT DISTINCT ON(source) source,CASE WHEN completed_at>p_cutoff THEN 'running' ELSE status END AS status,CASE WHEN completed_at>p_cutoff THEN NULL ELSE error_category END AS error_category,attempted_at FROM ccpun_admin.analytics_daily_batch WHERE attempted_at<=p_cutoff ORDER BY source,attempted_at DESC),
reports AS (SELECT DISTINCT ON(r.report) r.report,r.data,b.source FROM ccpun_admin.analytics_completed_report r JOIN ccpun_admin.analytics_daily_batch b USING(batch_id) WHERE b.status='completed' AND b.completed_at<=p_cutoff ORDER BY r.report,CASE WHEN r.report IN('gsc-daily-page','gsc-daily-query-page','ga4-daily-organic','ga4-content-events') THEN (r.data->>'periodEnd')::date END DESC NULLS LAST,b.completed_at DESC)
SELECT jsonb_build_object(
  'sources',(SELECT jsonb_agg(jsonb_build_object('source',s.source,'lastAttemptAt',to_char(a.attempted_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'lastAttemptStatus',a.status,'lastError',a.error_category) ORDER BY s.source) FROM sources s LEFT JOIN attempts a USING(source)),
  'datasets',COALESCE((SELECT jsonb_agg(r.data||jsonb_build_object('lastAttemptAt',to_char(a.attempted_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'lastAttemptStatus',a.status) ORDER BY r.report) FROM reports r LEFT JOIN attempts a USING(source)),'[]'::jsonb))
$analytics_read$;

-- checksum-source-end
INSERT INTO ccpun_admin.schema_migration(version,checksum) VALUES('20260927_marketing_local_analysis_v2','sha256:eb0d7a8a1637ccde4bc17d5bc60952da831aec8736123eb42970c467e5306f30') ON CONFLICT(version) DO NOTHING;
COMMIT;
