BEGIN;
SET LOCAL lock_timeout='5s';
SELECT 1 / CASE WHEN current_database()='neondb' THEN 1 ELSE 0 END AS database_guard;
SELECT 1 / CASE WHEN EXISTS(SELECT 1 FROM pg_roles WHERE rolname='ccpun_admin_runtime' AND NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole AND NOT rolbypassrls) THEN 1 ELSE 0 END AS role_guard;
SELECT 1 / CASE WHEN EXISTS(SELECT 1 FROM ccpun_admin.local_ai_identity WHERE singleton AND database_name='neondb' AND migration_version='20260919_local_ai_control_plane_v1' AND migration_checksum='sha256:b49fe8d024c279710eb4eb3b45b06e40ffc960a3ec57b21792c63c98514ceef6' AND ((lane='uat' AND project_id='young-term-47483330' AND branch_id='br-crimson-mouse-az7ajkv8' AND endpoint_id='ep-mute-frost-aztvz394') OR (lane='production' AND project_id='lively-bar-43618798' AND branch_id='br-long-resonance-b3ys5xrv' AND endpoint_id='ep-broad-butterfly-b3ro7u8w'))) THEN 1 ELSE 0 END AS identity_guard;
SELECT 1 / CASE WHEN EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version='20260928_marketing_cloud_prompt_v2' AND checksum='sha256:0fdd5ea1ac71e1de301536336eead7cc839973a0c3f8492dd10651226a79ee7c') THEN 1 ELSE 0 END AS prerequisite_guard;
SELECT pg_advisory_xact_lock(hashtext('ccpun_admin:20260928_marketing_cloud_timeout_v3'));
SELECT 1 / CASE WHEN NOT EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version='20260928_marketing_cloud_timeout_v3' AND checksum<>'sha256:d37f6baf16ef77b21c05a664d77dd6cd7427b74de60d1cf7557ee581da6ff5f0') THEN 1 ELSE 0 END AS checksum_guard;
-- checksum-source-begin
CREATE OR REPLACE FUNCTION ccpun_admin.marketing_analysis_json(a ccpun_admin.marketing_analysis) RETURNS jsonb LANGUAGE sql STABLE SET search_path=pg_catalog,ccpun_admin AS $shape$
SELECT jsonb_build_object('analysisId',a.analysis_id,'jobId',a.job_id,'status',CASE WHEN a.validation_status='validated' AND a.period_end<(ccpun_admin.marketing_window(a.window_key,least((now() AT TIME ZONE 'America/Los_Angeles')::date-3,(now() AT TIME ZONE 'Asia/Bangkok')::date-1))->>'currentEnd')::date THEN 'stale' WHEN a.validation_status='validated' THEN 'ready' WHEN c.status='reserved' AND c.reserved_at<now()-interval '30 minutes' THEN 'failed' WHEN c.status='reserved' THEN 'running' WHEN c.status='failed' THEN 'failed' WHEN j.status='leased' THEN 'running' WHEN a.validation_status='rejected' OR j.status IN('failed','cancelled','expired','reconciliation-required') THEN 'failed' WHEN a.job_id IS NULL THEN 'prepared' ELSE 'queued' END,'promptVersion',a.prompt_version,'analysisType',a.analysis_type,'period',a.input_json->'period','createdAt',a.created_at,'completedAt',a.validated_at,'modelName',CASE WHEN c.status='ready' THEN c.model ELSE j.model_name END,'inferenceProvider',CASE WHEN c.status='ready' THEN c.provider WHEN j.job_id IS NOT NULL THEN 'local' ELSE NULL END,'cloudUsage',CASE WHEN c.status='ready' THEN jsonb_build_object('inputTokens',c.input_tokens,'outputTokens',c.output_tokens) ELSE NULL END,'inputHash',a.input_hash,'sourceManifest',a.source_manifest,'inferenceProfile',(SELECT t.inference_profile FROM ccpun_admin.marketing_analysis_attempt t WHERE t.job_id=a.job_id),'attempts',(SELECT coalesce(jsonb_agg(jsonb_build_object('generation',t.generation,'jobId',t.job_id,'parentFailedJobId',t.parent_failed_job_id,'inferenceProfile',t.inference_profile,'provenance',t.provenance,'attemptCount',q.attempt_count,'maxAttempts',q.max_attempts,'status',q.status,'errorCategory',q.error_category,'capturedAt',t.captured_at) ORDER BY t.generation),'[]') FROM ccpun_admin.marketing_analysis_attempt t JOIN ccpun_admin.local_ai_job q USING(job_id) WHERE t.analysis_id=a.analysis_id),'output',CASE WHEN a.validation_status='validated' AND (c.status='ready' OR j.review_status IN('pending','approved')) THEN a.output_json END) FROM(SELECT 1) x LEFT JOIN ccpun_admin.local_ai_job j ON j.job_id=a.job_id LEFT JOIN ccpun_admin.marketing_cloud_attempt c ON c.analysis_id=a.analysis_id $shape$;
CREATE OR REPLACE FUNCTION ccpun_admin.admin_marketing_analysis_status(p_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,ccpun_admin AS $status$
SELECT jsonb_build_object('analysisId',a.analysis_id,'jobId',a.job_id,'status',CASE WHEN a.validation_status='validated' AND a.period_end<(ccpun_admin.marketing_window(a.window_key,least((now() AT TIME ZONE 'America/Los_Angeles')::date-3,(now() AT TIME ZONE 'Asia/Bangkok')::date-1))->>'currentEnd')::date THEN 'stale' WHEN a.validation_status='validated' THEN 'ready' WHEN c.status='reserved' AND c.reserved_at<now()-interval '30 minutes' THEN 'failed' WHEN c.status='reserved' THEN 'running' WHEN c.status='failed' THEN 'failed' WHEN j.status='leased' THEN 'running' WHEN a.validation_status='rejected' OR j.status IN('failed','cancelled','expired','reconciliation-required') THEN 'failed' WHEN a.job_id IS NULL THEN 'prepared' ELSE 'queued' END,'workerSucceeded',coalesce(j.status='succeeded',false),'cloudStatus',c.status) FROM ccpun_admin.marketing_analysis a LEFT JOIN ccpun_admin.local_ai_job j USING(job_id) LEFT JOIN ccpun_admin.marketing_cloud_attempt c ON c.analysis_id=a.analysis_id WHERE a.analysis_id=p_id $status$;
-- checksum-source-end
INSERT INTO ccpun_admin.schema_migration(version,checksum) VALUES('20260928_marketing_cloud_timeout_v3','sha256:d37f6baf16ef77b21c05a664d77dd6cd7427b74de60d1cf7557ee581da6ff5f0') ON CONFLICT(version) DO NOTHING;
COMMIT;
