import { NextResponse } from "next/server";
import { z } from "zod";
import { isN8nExportRequestAuthorized } from "@/lib/admin/agent-os/export-service-auth";
import { shiftAnalyticsDate } from "@/lib/admin/analytics/model";
import { marketingProviderEnd } from "@/lib/admin/marketing/model";
import { readMarketingCalendar } from "@/lib/admin/marketing/window-store";
import { collectMarketingWindow, planMarketingBackfill } from "@/lib/admin/marketing/collect";
import { collectMarketingIdentity } from "@/lib/admin/marketing/identity";
export const runtime="nodejs";export const dynamic="force-dynamic";export const maxDuration=120;
const headers={"Cache-Control":"private, no-store","X-Robots-Tag":"noindex, nofollow, noarchive","X-Content-Type-Options":"nosniff"};
const input=z.discriminatedUnion("operation",[z.object({operation:z.literal("identity")}).strict(),z.object({operation:z.literal("collect"),source:z.enum(["gsc","ga4"]),startDate:z.iso.date().optional(),endDate:z.iso.date().optional(),lookbackDays:z.number().int().min(1).max(56).optional()}).strict(),z.object({operation:z.literal("backfill"),source:z.enum(["gsc","ga4"]),cursorEnd:z.iso.date().optional()}).strict()]);
export async function POST(request:Request){if(!isN8nExportRequestAuthorized(request))return NextResponse.json({error:"unauthorized"},{status:401,headers});try{const reader=request.body?.getReader();if(!reader)throw new Error("INVALID");const chunks:Uint8Array[]=[];let size=0;for(;;){const c=await reader.read();if(c.done)break;size+=c.value.length;if(size>2048){await reader.cancel();return NextResponse.json({error:"payload-too-large"},{status:413,headers});}chunks.push(c.value);}const parsed=input.safeParse(JSON.parse(Buffer.concat(chunks).toString("utf8")));if(!parsed.success)return NextResponse.json({error:"invalid-request"},{status:400,headers});if(parsed.data.operation==="identity")return NextResponse.json(await collectMarketingIdentity(),{headers});const value=parsed.data,maxEnd=marketingProviderEnd(value.source,new Date(),await readMarketingCalendar(value.source)),commonEnd=marketingProviderEnd("gsc"),end=value.operation==="backfill"?(value.cursorEnd??maxEnd):(value.endDate??(maxEnd<commonEnd?maxEnd:commonEnd));if(value.operation==="backfill"){if(end>maxEnd)return NextResponse.json({error:"invalid-window"},{status:400,headers});const plan=planMarketingBackfill(value.source,end,maxEnd);if(!plan.window)return NextResponse.json(plan,{headers});const result=await collectMarketingWindow(value.source,plan.window.start,plan.window.end);const complete=result.status==="completed"&&result.reportCoverage==="complete";return NextResponse.json({...result,earliestAllowedStart:plan.earliestAllowedStart,limitKind:plan.limitKind,nextEnd:complete?plan.nextEnd:null,backfillStatus:complete?(plan.nextEnd?"continue":"limit-reached"):result.status==="duplicate"?"already-collected":"needs-review"},{headers});}const start=value.startDate??shiftAnalyticsDate(end,-((value.lookbackDays??56)-1));const days=(Date.parse(end)-Date.parse(start))/86400000;if(days<0||days>55||end>maxEnd)return NextResponse.json({error:"invalid-window"},{status:400,headers});return NextResponse.json(await collectMarketingWindow(value.source,start,end),{headers});}catch{return NextResponse.json({error:"marketing-refresh-unavailable"},{status:503,headers});}}
