import test, { before, after } from "node:test";
import assert from "node:assert/strict";
import { normalizeMarketingUrl, marketingActionSchema, marketingProviderEnd } from "../../lib/admin/marketing/model";
import { readFileSync } from "node:fs";
import { registerHooks } from "node:module";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
const directory=mkdtempSync(join(tmpdir(),"ccpun-marketing-test-"));const stub=join(directory,"server-only.cjs");writeFileSync(stub,"module.exports={};");registerHooks({resolve(s,c,next){if(s==="server-only")return{url:pathToFileURL(stub).href,shortCircuit:true};return next(s,c);}});
let readMarketingWorkspaceModels:typeof import("../../lib/admin/marketing/store").readMarketingWorkspaceModels;
let collectMarketingDaily: typeof import("../../lib/admin/marketing/collect").collectMarketingDaily;
let normalizeMarketingGa4: typeof import("../../lib/admin/marketing/collect").normalizeMarketingGa4;
before(async()=>{readMarketingWorkspaceModels=(await import("../../lib/admin/marketing/store")).readMarketingWorkspaceModels;collectMarketingDaily=(await import("../../lib/admin/marketing/collect")).collectMarketingDaily;normalizeMarketingGa4=(await import("../../lib/admin/marketing/collect")).normalizeMarketingGa4;});after(()=>rmSync(directory,{recursive:true,force:true}));
test("canonical identity strips query/fragment, scopes hosts, normalizes trailing slash",()=>{assert.equal(normalizeMarketingUrl("/blog/health/a/?email=private@example.com#cta"),"https://ccpun.com/blog/health/a");assert.equal(normalizeMarketingUrl("https://www.ccpun.com/ci-planning/"),"https://ccpun.com/ci-planning");assert.equal(normalizeMarketingUrl("https://attacker.example/blog/a"),null);assert.equal(normalizeMarketingUrl("javascript:alert(1)"),null);});
test("native GA4 dates and event page paths reject unsupported dimensions/PII and impossible counters",()=>{const raw={dimensionHeaders:[{name:"date"},{name:"landingPage"}],metricHeaders:[{name:"sessions"},{name:"engagedSessions"}],rowCount:1,rows:[{dimensionValues:[{value:"20260920"},{value:"/blog/a"}],metricValues:[{value:"10"},{value:"4"}]}],metadata:{timeZone:"Asia/Bangkok"}};assert.equal(normalizeMarketingGa4("ga4-daily-organic",raw,"2026-09-01","2026-09-24").rows[0]?.["วันที่"],"2026-09-20");assert.throws(()=>normalizeMarketingGa4("ga4-daily-organic",{...raw,rows:[{...raw.rows[0],dimensionValues:[{value:"20260920"},{value:"/blog/a?email=private"}]}]},"2026-09-01","2026-09-24"));assert.throws(()=>normalizeMarketingGa4("ga4-daily-organic",{...raw,rows:[{...raw.rows[0],metricValues:[{value:"2"},{value:"4"}]}]},"2026-09-01","2026-09-24"));assert.throws(()=>normalizeMarketingGa4("ga4-daily-organic",raw,"2026-09-21","2026-09-24"));});
test("action schema preserves explicit human fields and rejects invented outcome metric/status",()=>{const action={version:0,assetId:null,priority:"medium",actionType:"investigation",description:"Inspect current evidence",expectedMetric:"search_clicks",owner:"COO",status:"backlog",executedAt:null,measurementDays:14,notes:"Human note",hypothesis:"Title may influence CTR",confounderNotes:"Seasonality"};assert.equal(marketingActionSchema.parse(action).notes,"Human note");assert.equal(marketingActionSchema.safeParse({...action,status:"ai-approved"}).success,false);assert.equal(marketingActionSchema.safeParse({...action,expectedMetric:"confirmed_leads"}).success,false);});
test("schema safeguards complete-window replacement, pinned baseline and private execution boundary",()=>{const sql=readFileSync("db/migrations/20260927_marketing_foundation_v1.sql","utf8");assert.match(sql,/newer\.collected_at,newer\.batch_id/);assert.match(sql,/newer\.complete/);assert.match(sql,/baseline_manifest IS NULL/);assert.match(sql,/version=\(p->>'version'\)::integer/);assert.match(sql,/source_as_of_date date, source_as_of_ts timestamptz/);assert.match(sql,/FROM PUBLIC,ccpun_admin_runtime/);assert.match(sql,/marketing_social_unified/);assert.doesNotMatch(sql,/DELETE FROM|TRUNCATE TABLE|GRANT SELECT/i);});

test("provider maturity uses native date across Bangkok/Los Angeles midnight",()=>{assert.equal(marketingProviderEnd("gsc",new Date("2026-09-26T23:00:00Z")),"2026-09-23");assert.equal(marketingProviderEnd("ga4",new Date("2026-09-26T23:00:00Z"),"Asia/Bangkok"),"2026-09-26");});

test("bounded daily campaign collection reuses native report grain and preserves legacy all-traffic request",async()=>{const {ga4MarketingRequest}=await import("../../lib/admin/analytics/model");const captured:Array<{report:string,body:Record<string,unknown>}> = [];const fetchForReport=(report:string):typeof fetch=>async(_url,init)=>{const body=JSON.parse(String(init?.body));captured.push({report,body});const dimensions=body.dimensions.map((x:{name:string})=>x.name),metrics=body.metrics.map((x:{name:string})=>x.name);const values=report==="ga4-session-performance"?["20260924","google / organic","(not set)","/ci-planning"]:report==="ga4-content-events"?["20260924","ci_calculator_complete","/ci-planning"]:["20260924","/ci-planning"];return new Response(JSON.stringify({dimensionHeaders:dimensions.map((name:string)=>({name})),metricHeaders:metrics.map((name:string)=>({name})),rows:[{dimensionValues:values.map(value=>({value})),metricValues:(report==="ga4-session-performance"?["10","8","3.5","0.2"]:report==="ga4-content-events"?["5"]:["10","8"]).map(value=>({value}))}],rowCount:1,metadata:{timeZone:"Asia/Bangkok"}}),{status:200});};const rows=await collectMarketingDaily({source:"ga4",token:"synthetic-token",resource:"fixture",start:"2026-08-01",end:"2026-09-24"},fetchForReport,Date.now()+85000);assert.equal(rows.length,3);const campaign=rows.find(r=>r.report==="ga4-session-performance")!;assert.equal(campaign.rows[0]?.["วันที่"],"2026-09-24");assert.equal(campaign.rows[0]?.["แหล่งทราฟฟิก / Medium"],"google / organic");assert.equal(campaign.rows[0]?.["แคมเปญ"],"(not set)");assert.equal(campaign.rows[0]?.["Key events"],3.5);assert.equal(campaign.rows[0]?.["Session key event rate (%)"],20);assert.match(JSON.stringify(captured.find(r=>r.report==="ga4-session-performance")?.body.dimensionFilter),/hostName/);assert.equal("dimensionFilter" in ga4MarketingRequest("ga4-session-performance","2026-09-01","2026-09-24"),false);assert.match(campaign.limitations?.join(" ")??"",/blog excluded/);});

test("workspace snapshot uses one statement clock and safe unavailable models without source refresh",async()=>{const data=await readMarketingWorkspaceModels("2026-09-01T00:00:00Z",{});assert.equal(data.weekly.state,"unavailable");assert.equal(data.monthly.state,"unavailable");assert.equal(data.weekly.generatedAt,data.monthly.generatedAt);assert.equal(data.cutoff,data.weekly.generatedAt);assert.notEqual(data.cutoff,"2026-09-01T00:00:00Z");assert.equal(data.weekly.kpis.length,0);const source=readFileSync("lib/admin/marketing/store.ts","utf8").split("export async function readMarketingWorkspaceModels")[1]!.split("export async function saveMarketingAction")[0]!;assert.equal((source.match(/\.query\(/g)??[]).length,1);assert.match(source,/admin_read_marketing_v2\('this_week',statement_timestamp\(\)\)/);assert.match(source,/admin_read_marketing_v2\('this_month',statement_timestamp\(\)\)/);assert.doesNotMatch(source,/fetch\(|sanityFetch|collectMarketing|Promise\.all/);});
