import type { CharacterProfile } from './types';

export const MONEY_STORY_CHARACTERS: CharacterProfile[] = [
  {
    id: 'gam',
    name: 'แก้ม',
    role: 'พนักงานร้านอาหาร',
    archetype: 'เริ่มจากเงินกันชนน้อย',
    challenge: 'ทำให้เงินสดพอรับเหตุไม่คาดคิด โดยยังช่วยค่าใช้จ่ายที่บ้านได้',
    story: 'รายได้พอหมุนทุกเดือนและช่วยค่าใช้จ่ายที่บ้าน เป้าหมายคือมีเงินก้อนที่ทำให้พักหายใจได้มากขึ้น',
    trait: 'ภาระไม่เยอะมาก แต่เงินกันชนยังบาง',
    baseIncome: 19000,
    incomeStability: 'stable',
    startingCash: 12000,
    startingInvestments: 0,
    fixedExpenses: 12500,
    healthBenefitCap: 9000,
    dependents: 1,
    hasCar: false,
    hasHome: false,
    existingProtections: [],
    startingDebts: [],
    goal: { label: 'สร้างเงินสำหรับเป้าหมายให้ถึง 55,000 บาท', targetNetPosition: 55000 },
  },
  {
    id: 'ton',
    name: 'ต้น',
    role: 'พนักงานช่วงเริ่มทำงาน',
    archetype: 'เริ่มงาน มีหนี้ก้อนแรก',
    challenge: 'สร้างเงินก้อนแรกให้โต โดยไม่ให้หนี้เดิมกินพื้นที่ของรายได้',
    story: 'เริ่มทำงานได้ไม่นาน มีเงินเก็บก้อนแรกและอยากให้ปลายปีเห็นความคืบหน้าชัดขึ้น',
    trait: 'ภาระยังไม่สูง แต่มีหนี้ก้อนเล็กติดมาด้วย',
    baseIncome: 28000,
    incomeStability: 'stable',
    startingCash: 35000,
    startingInvestments: 15000,
    fixedExpenses: 16000,
    healthBenefitCap: 12000,
    dependents: 0,
    hasCar: false,
    hasHome: false,
    existingProtections: [{ type: 'health', monthlyPremium: 0 }],
    startingDebts: [
      { id: 'ton-existing', label: 'หนี้เดิม', principalRemaining: 18000, monthlyRate: 0.006, monthlyPayment: 1800, remainingMonths: 12 },
    ],
    goal: { label: 'สร้างเงินสำหรับเป้าหมายให้ถึง 135,000 บาท', targetNetPosition: 135000 },
  },
  {
    id: 'meen',
    name: 'มีน',
    role: 'ฟรีแลนซ์',
    archetype: 'รายได้ขึ้นลง',
    challenge: 'รักษาเงินสดให้พอในเดือนเงียบ และเลือกจังหวะลงทุนให้เหมาะ',
    story: 'บางเดือนงานแน่น บางเดือนเงียบ จึงต้องบาลานซ์ระหว่างเงินสดกับการต่อยอดเงินที่มี',
    trait: 'รายได้ผันผวน แต่มีเงินกันชนอยู่บ้าง',
    baseIncome: 42000,
    incomeStability: 'variable',
    startingCash: 80000,
    startingInvestments: 40000,
    fixedExpenses: 24000,
    healthBenefitCap: 7000,
    dependents: 0,
    hasCar: false,
    hasHome: false,
    existingProtections: [{ type: 'health', monthlyPremium: 900 }],
    startingDebts: [],
    goal: { label: 'สร้างเงินสำหรับเป้าหมายให้ถึง 250,000 บาท', targetNetPosition: 250000 },
  },
  {
    id: 'nut',
    name: 'นัท',
    role: 'พนักงานบริษัท',
    archetype: 'รายได้คงที่ มีรถและหนี้',
    challenge: 'บาลานซ์เงินสด พอร์ต และภาระรถที่เดินทุกเดือน',
    story: 'รายได้ค่อนข้างนิ่ง มีรถและเงินลงทุน แต่มีภาระผ่อนที่ต้องเดินต่อทุกเดือน',
    trait: 'ฐานเริ่มดี แต่ภาระประจำทำให้เงินเหลือต่อเดือนไม่มาก',
    baseIncome: 52000,
    incomeStability: 'stable',
    startingCash: 90000,
    startingInvestments: 65000,
    fixedExpenses: 29000,
    healthBenefitCap: 18000,
    dependents: 0,
    hasCar: true,
    hasHome: false,
    existingProtections: [
      { type: 'health', monthlyPremium: 0 },
      { type: 'motor', monthlyPremium: 700 },
    ],
    startingDebts: [
      { id: 'nut-car', label: 'ภาระรถ', principalRemaining: 140000, monthlyRate: 0.005, monthlyPayment: 7000, remainingMonths: 24 },
    ],
    goal: { label: 'สร้างเงินสำหรับเป้าหมายให้ถึง 190,000 บาท', targetNetPosition: 190000 },
  },
  {
    id: 'fon',
    name: 'ฝน',
    role: 'หัวหน้าทีมและคนดูแลครอบครัว',
    archetype: 'รายได้ดี แต่มีคนพึ่งพา',
    challenge: 'ดูแลครอบครัว พร้อมรักษาเงินกันชนและเป้าหมายระยะยาว',
    story: 'มีรายได้ค่อนข้างดี แต่ต้องดูแลคนในบ้านและมีหลายเป้าหมายเดินพร้อมกัน',
    trait: 'มีคนพึ่งรายได้ จึงต้องคิดทั้งวันนี้และผลกระทบต่อครอบครัว',
    baseIncome: 68000,
    incomeStability: 'stable',
    startingCash: 120000,
    startingInvestments: 110000,
    fixedExpenses: 40000,
    healthBenefitCap: 22000,
    dependents: 2,
    hasCar: true,
    hasHome: false,
    existingProtections: [
      { type: 'health', monthlyPremium: 700 },
      { type: 'life', monthlyPremium: 600 },
      { type: 'motor', monthlyPremium: 850 },
    ],
    startingDebts: [
      { id: 'fon-debt', label: 'ภาระเดิม', principalRemaining: 90000, monthlyRate: 0.006, monthlyPayment: 6000, remainingMonths: 18 },
    ],
    goal: { label: 'สร้างเงินสำหรับเป้าหมายให้ถึง 350,000 บาท', targetNetPosition: 350000 },
  },
  {
    id: 'win',
    name: 'วิน',
    role: 'ผู้จัดการสายเทค',
    archetype: 'รายได้สูง ภาระก็สูง',
    challenge: 'ไม่ให้บ้าน รถ และไลฟ์สไตล์กินความคล่องตัวจนหมด',
    story: 'รายได้สูงขึ้นเร็ว แต่ค่าใช้จ่าย บ้าน รถ และภาระประจำโตตามมาด้วย',
    trait: 'ตัวเลขรายได้ดูสบาย แต่ความคล่องตัวไม่ได้สูงอย่างที่คิด',
    baseIncome: 110000,
    incomeStability: 'stable',
    startingCash: 180000,
    startingInvestments: 300000,
    fixedExpenses: 67000,
    healthBenefitCap: 30000,
    dependents: 1,
    hasCar: true,
    hasHome: true,
    existingProtections: [
      { type: 'health', monthlyPremium: 1200 },
      { type: 'motor', monthlyPremium: 850 },
      { type: 'home', monthlyPremium: 500 },
    ],
    startingDebts: [
      { id: 'win-home', label: 'ภาระบ้านและรถ', principalRemaining: 360000, monthlyRate: 0.006, monthlyPayment: 18000, remainingMonths: 30 },
    ],
    goal: { label: 'สร้างเงินสำหรับเป้าหมายให้ถึง 450,000 บาท', targetNetPosition: 450000 },
  },
  {
    id: 'ploy',
    name: 'พลอย',
    role: 'เจ้าของธุรกิจ',
    archetype: 'สินทรัพย์เยอะ รายได้ผันผวน',
    challenge: 'บริหารกระแสเงินสดเมื่อรายได้ไม่เท่ากันทุกเดือนและมีครอบครัว',
    story: 'มีสินทรัพย์และรายได้หลายทาง แต่รายได้ไม่เท่ากันทุกเดือนและมีครอบครัวให้ดูแล',
    trait: 'ทรัพยากรเยอะขึ้น แต่ความผันผวนก็ใหญ่ขึ้นตาม',
    baseIncome: 140000,
    incomeStability: 'business',
    startingCash: 300000,
    startingInvestments: 450000,
    fixedExpenses: 70000,
    healthBenefitCap: 25000,
    dependents: 2,
    hasCar: true,
    hasHome: true,
    existingProtections: [
      { type: 'health', monthlyPremium: 1200 },
      { type: 'life', monthlyPremium: 650 },
      { type: 'motor', monthlyPremium: 850 },
    ],
    startingDebts: [
      { id: 'ploy-business', label: 'ภาระธุรกิจและทรัพย์สิน', principalRemaining: 520000, monthlyRate: 0.007, monthlyPayment: 28000, remainingMonths: 30 },
    ],
    goal: { label: 'สร้างเงินสำหรับเป้าหมายให้ถึง 780,000 บาท', targetNetPosition: 780000 },
  },
  {
    id: 'poom',
    name: 'ภูมิ',
    role: 'ผู้บริหารธุรกิจครอบครัว',
    archetype: 'ฐานใหญ่ ความเสี่ยงก็ใหญ่',
    challenge: 'รักษาฐานสินทรัพย์พร้อมรับเหตุการณ์ที่กระทบเป็นเงินก้อนใหญ่',
    story: 'มีเงินและสินทรัพย์ตั้งต้นมากกว่าคนส่วนใหญ่ แต่ต้องบริหารภาระและความเสี่ยงหลายด้านพร้อมกัน',
    trait: 'รับแรงกระแทกได้มาก แต่เหตุการณ์ใหญ่ก็มีมูลค่ากระทบสูง',
    baseIncome: 220000,
    incomeStability: 'business',
    startingCash: 550000,
    startingInvestments: 1200000,
    fixedExpenses: 125000,
    healthBenefitCap: 35000,
    dependents: 3,
    hasCar: true,
    hasHome: true,
    existingProtections: [
      { type: 'health', monthlyPremium: 1500 },
      { type: 'critical', monthlyPremium: 900 },
      { type: 'life', monthlyPremium: 650 },
      { type: 'motor', monthlyPremium: 1000 },
      { type: 'home', monthlyPremium: 600 },
    ],
    startingDebts: [
      { id: 'poom-assets', label: 'ภาระทรัพย์สิน', principalRemaining: 780000, monthlyRate: 0.006, monthlyPayment: 35000, remainingMonths: 36 },
    ],
    goal: { label: 'สร้างเงินสำหรับเป้าหมายให้ถึง 1,650,000 บาท', targetNetPosition: 1650000 },
  },
];

export function getMoneyStoryCharacter(id: string): CharacterProfile {
  return MONEY_STORY_CHARACTERS.find((character) => character.id === id) ?? MONEY_STORY_CHARACTERS[0];
}
