import { NextResponse } from "next/server";
import { z } from "zod";
import { isN8nExportRequestAuthorized } from "@/lib/admin/agent-os/export-service-auth";
import { marketingWindowSchema } from "@/lib/admin/marketing/model";
import { captureMarketingMeasurements, prepareMarketingAnalysis, enqueueMarketingAnalysis, marketingAnalysisStatus, validateMarketingAnalysis, reserveMarketingCloudFallback, submitMarketingCloudFallback, failMarketingCloudFallback, reserveMarketingCloudReview, submitMarketingCloudReview, failMarketingCloudReview } from "@/lib/admin/marketing/analysis";
export const runtime="nodejs";export const dynamic="force-dynamic";export const maxDuration=60;
const headers={"Cache-Control":"private, no-store","X-Robots-Tag":"noindex, nofollow, noarchive","X-Content-Type-Options":"nosniff"};
const id=z.string().uuid(),hash=z.string().regex(/^[a-f0-9]{64}$/);
const input=z.discriminatedUnion("operation",[z.object({operation:z.literal("measure")}).strict(),z.object({operation:z.literal("prepare"),window:marketingWindowSchema}).strict(),z.object({operation:z.literal("enqueue"),analysisId:id,inputHash:hash}).strict(),z.object({operation:z.enum(["status","validate"]),analysisId:id}).strict(),z.object({operation:z.literal("reserveCloud"),analysisId:id,inputHash:hash}).strict(),z.object({operation:z.literal("submitCloud"),analysisId:id,inputHash:hash,reservationId:id,selection:z.unknown(),usage:z.object({inputTokens:z.number().int().nonnegative().max(100000),outputTokens:z.number().int().nonnegative().max(100000)}).strict()}).strict(),z.object({operation:z.literal("failCloud"),analysisId:id,inputHash:hash,reservationId:id,reason:z.enum(["api-error","model-output-invalid","timeout","workflow-error"])}).strict(),z.object({operation:z.literal("reserveReview"),analysisId:id,inputHash:hash}).strict(),z.object({operation:z.literal("submitReview"),analysisId:id,inputHash:hash,reservationId:id,localOutputDigest:hash,verdict:z.unknown(),usage:z.object({inputTokens:z.number().int().nonnegative().max(100000),outputTokens:z.number().int().nonnegative().max(100000)}).strict()}).strict(),z.object({operation:z.literal("failReview"),analysisId:id,inputHash:hash,reservationId:id,localOutputDigest:hash,reason:z.enum(["api-error","model-output-invalid","timeout","workflow-error"])}).strict()]);
export async function POST(request:Request){if(!isN8nExportRequestAuthorized(request))return NextResponse.json({error:"unauthorized"},{status:401,headers});try{const reader=request.body?.getReader();if(!reader)throw new Error("INVALID");const chunks:Uint8Array[]=[];let size=0;for(;;){const c=await reader.read();if(c.done)break;size+=c.value.length;if(size>24000){await reader.cancel();return NextResponse.json({error:"payload-too-large"},{status:413,headers});}chunks.push(c.value);}const p=input.safeParse(JSON.parse(Buffer.concat(chunks).toString("utf8")));if(!p.success)return NextResponse.json({error:"invalid-analysis-operation"},{status:400,headers});const v=p.data;const data=v.operation==="measure"?await captureMarketingMeasurements():v.operation==="prepare"?await prepareMarketingAnalysis(v.window):v.operation==="enqueue"?await enqueueMarketingAnalysis(v.analysisId,v.inputHash):v.operation==="status"?await marketingAnalysisStatus(v.analysisId):v.operation==="validate"?await validateMarketingAnalysis(v.analysisId):v.operation==="reserveCloud"?await reserveMarketingCloudFallback(v):v.operation==="submitCloud"?await submitMarketingCloudFallback(v):v.operation==="failCloud"?await failMarketingCloudFallback(v):v.operation==="reserveReview"?await reserveMarketingCloudReview(v):v.operation==="submitReview"?await submitMarketingCloudReview(v):await failMarketingCloudReview(v);return NextResponse.json(data,{headers});}catch{return NextResponse.json({status:"unavailable",error:"marketing-analysis-unavailable",factsRemainAvailable:true},{status:503,headers});}}
