import { NextResponse } from "next/server";
import { z } from "zod";
import { isN8nExportRequestAuthorized } from "@/lib/admin/agent-os/export-service-auth";
import { marketingWindowSchema } from "@/lib/admin/marketing/model";
import { captureMarketingMeasurements, prepareMarketingAnalysis, enqueueMarketingAnalysis, marketingAnalysisStatus, validateMarketingAnalysis } from "@/lib/admin/marketing/analysis";
export const runtime="nodejs";export const dynamic="force-dynamic";export const maxDuration=60;
const headers={"Cache-Control":"private, no-store","X-Robots-Tag":"noindex, nofollow, noarchive","X-Content-Type-Options":"nosniff"};
const input=z.discriminatedUnion("operation",[z.object({operation:z.literal("measure")}).strict(),z.object({operation:z.literal("prepare"),window:marketingWindowSchema}).strict(),z.object({operation:z.literal("enqueue"),analysisId:z.string().uuid(),inputHash:z.string().regex(/^[a-f0-9]{64}$/)}).strict(),z.object({operation:z.enum(["status","validate"]),analysisId:z.string().uuid()}).strict()]);
export async function POST(request:Request){if(!isN8nExportRequestAuthorized(request))return NextResponse.json({error:"unauthorized"},{status:401,headers});try{const reader=request.body?.getReader();if(!reader)throw new Error("INVALID");const chunks:Uint8Array[]=[];let size=0;for(;;){const c=await reader.read();if(c.done)break;size+=c.value.length;if(size>2048){await reader.cancel();return NextResponse.json({error:"payload-too-large"},{status:413,headers});}chunks.push(c.value);}const p=input.safeParse(JSON.parse(Buffer.concat(chunks).toString("utf8")));if(!p.success)return NextResponse.json({error:"invalid-analysis-operation"},{status:400,headers});const v=p.data;const data=v.operation==="measure"?await captureMarketingMeasurements():v.operation==="prepare"?await prepareMarketingAnalysis(v.window):v.operation==="enqueue"?await enqueueMarketingAnalysis(v.analysisId,v.inputHash):v.operation==="status"?await marketingAnalysisStatus(v.analysisId):await validateMarketingAnalysis(v.analysisId);return NextResponse.json(data,{headers});}catch{return NextResponse.json({status:"unavailable",error:"marketing-analysis-unavailable",factsRemainAvailable:true},{status:503,headers});}}
