import type { AnalyticsDataset } from "@/lib/admin/analytics/model";
import { buildPerformanceTables } from "@/lib/admin/analytics/performance";

const link = "inline-flex min-h-11 items-center rounded-lg border border-white/20 px-3 py-2 text-sm text-[#e0c985] hover:bg-white/5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#e0c985]";
const text = (value: unknown) => value === null || value === undefined || value === "" ? "ไม่ทราบ" : String(value);
export function PerformanceInsights({ datasets }: { datasets: AnalyticsDataset[] }) {
  const tables = buildPerformanceTables(datasets), seo = tables[0]!, gaps = tables[1]!;
  return <section className="mt-8 min-w-0 border-t border-white/15 pt-6" aria-labelledby="performance-insights-heading">
    <h2 id="performance-insights-heading" className="text-xl font-semibold">เอาข้อมูลไปทำอะไรต่อ</h2>
    <p className="mt-2 max-w-3xl text-sm leading-6 text-white/70">เริ่มจากงานตรวจคำค้นและหน้าเป้าหมาย แล้วดูแคมเปญกับกิจกรรมที่เกิดบนเว็บ แยกไฟล์ตามเรื่องเพื่อทำ Pivot ต่อได้ Excel รวมชีตวิเคราะห์ไว้ด้วย</p>
    <div className="mt-4 flex flex-wrap gap-3">{tables.filter(table => table.rows.length).map(table => <a download key={table.view} className={link} href={`/api/admin/analytics/export/?view=${table.view}&format=csv`}>CSV · {table.title}</a>)}</div>
    <h3 className="mt-6 font-semibold">งานตรวจ SEO · {seo.rows.length.toLocaleString("th-TH")} รายการ</h3>
    <p className="mt-2 text-sm leading-6 text-white/65">{seo.guidance} เป็นข้อเสนอให้ตรวจงาน ไม่ใช่การรับประกันอันดับหรือยอดขาย</p>
    {seo.rows.length ? <div className="mt-4 max-w-full overflow-x-auto" tabIndex={0} role="region" aria-label="ตารางงานตรวจ SEO เลื่อนแนวนอนได้"><table className="w-full min-w-[720px] text-left text-sm"><caption className="pb-3 text-left text-xs text-white/60">แสดง {Math.min(10, seo.rows.length)} รายการแรก · CSV มีครบทุกแถว · วันที่ของ Google และ Ubersuggest แยกกัน</caption><thead><tr className="border-b border-white/20">{["คำค้น / หน้า", "งานที่ควรตรวจ", "หลักฐาน Google", "บริบท Ubersuggest"].map(title => <th key={title} scope="col" className="p-3 font-medium text-[#e0c985]">{title}</th>)}</tr></thead><tbody>{seo.rows.slice(0, 10).map((row, index) => <tr key={index} className="border-b border-white/10 align-top"><th scope="row" className="max-w-60 break-words p-3 font-medium">{text(row["คำค้น"])}<span className="mt-1 block text-xs font-normal text-white/60">{text(row["หน้าเป้าหมาย"])}</span></th><td className="max-w-60 p-3">{text(row["งานที่ควรตรวจ"])}<p className="mt-1 text-xs leading-5 text-white/60">{text(row["เหตุผล / กติกา"])}</p></td><td className="p-3 text-xs leading-5">แสดงผล: {text(row["การแสดงผล GSC"])}<br />คลิก: {text(row["คลิก GSC"])}<br />อันดับเฉลี่ย: {text(row["อันดับเฉลี่ย GSC"])}<br />{row["แหล่งข้อมูล"] === "gsc" ? `ถึง ${text(row["ข้อมูลต้นทาง ณ"])}` : "ยังไม่มีคำค้น GSC"}</td><td className="p-3 text-xs leading-5">Intent: {text(row["Intent Ubersuggest"])}<br />Volume: {text(row["Volume Ubersuggest"])}<br />อันดับต้นทาง: {text(row["อันดับ Ubersuggest"])}<br />ต้นทาง ณ {text(row["Ubersuggest ต้นทาง ณ"])}</td></tr>)}</tbody></table></div> : <p className="mt-3 text-sm text-white/60">ยังไม่มีรายงานคำค้นที่บันทึกไว้สำหรับเตรียมงาน SEO</p>}
    <details className="mt-6 border-y border-white/15 py-4" open><summary className="cursor-pointer font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#e0c985]">ก่อนวิเคราะห์งบและผลธุรกิจ ยังต้องมีอะไร</summary><p className="mt-3 text-sm leading-6 text-white/70">{gaps.guidance}</p><dl className="mt-3 grid gap-4 sm:grid-cols-2">{gaps.rows.map(row => <div key={String(row["ข้อมูล"])} className="min-w-0"><dt className="font-medium">{text(row["ข้อมูล"])}</dt><dd className="mt-1 text-xs leading-5 text-white/65"><span className="text-[#e0c985]">{text(row["สถานะ"])}</span><br />{text(row["ขั้นตอนต่อไป"])}</dd></div>)}</dl></details>
    {tables.slice(2).filter(table => table.rows.length).map(table => <p key={table.view} className="mt-3 text-sm leading-6 text-white/65"><strong className="font-medium text-white">{table.title}: </strong>{table.guidance}</p>)}
  </section>;
}
