import type { AnalyticsDataset } from "@/lib/admin/analytics/model";
import { buildPerformanceTables } from "@/lib/admin/analytics/performance";

const link = "inline-flex min-h-11 items-center rounded-lg border border-white/20 px-3 py-2 text-sm text-[#e0c985] hover:bg-white/5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#e0c985]";
const text = (value: unknown) => value === null || value === undefined || value === "" ? "ไม่ทราบ" : String(value);
const intentNames: Record<string, string> = { informational: "หาข้อมูล", commercial: "เปรียบเทียบก่อนซื้อ", transactional: "พร้อมทำรายการ", navigational: "หาเว็บหรือแบรนด์", mixed: "หลายเจตนา" };
const intent = (value: unknown) => value == null || value === "" ? "ไม่ทราบ" : intentNames[String(value).toLowerCase()] ?? "เจตนาอื่นที่ต้นทางระบุ";
const reason = (value: unknown) => text(value).replaceAll("ไม่ใช่ benchmark", "ไม่ใช่เกณฑ์อ้างอิง").replaceAll("benchmark", "เกณฑ์อ้างอิง").replaceAll("SERP", "หน้าผลการค้นหา").replaceAll("Intent/Volume", "เจตนาค้นหาและปริมาณค้นหา");
const guidance: Record<string, string> = {
  "seo-review": "เรียงตามจำนวนครั้งที่ปรากฏใน Google หากยังไม่มีข้อมูล Google ใช้ปริมาณค้นหาโดยประมาณจาก Ubersuggest เพื่อวางแผนเท่านั้น ไม่ใช่จำนวนผู้เข้าชมที่คาดว่าจะได้ อันดับที่ว่างหมายถึงไม่ทราบ",
  "measurement-gaps": "ยังคำนวณ CPA/ROAS (ต้นทุนต่อผลลัพธ์และผลตอบแทนโฆษณา) ไม่ได้ จนกว่าจะมีค่าใช้จ่ายกับผลธุรกิจจริงในช่วงเวลาเดียวกัน",
  "campaign-performance": "วิเคราะห์ตามวัน ช่องทาง แคมเปญ และหน้าเข้า รวมจำนวนเซสชันได้เฉพาะแถวที่ไม่ซ้ำขอบเขต ห้ามนำอัตราเหตุการณ์สำคัญของแต่ละแถวมาหาค่าเฉลี่ยตรง ๆ และเหตุการณ์สำคัญไม่ใช่จำนวนลูกค้า",
  "marketing-activities": "วิเคราะห์ตามวัน ประเภทกิจกรรม และจำนวนครั้งที่เกิด กิจกรรมหนึ่งอย่างเกิดซ้ำได้ จึงไม่ใช่จำนวนคนที่ไม่ซ้ำกัน จำนวนลูกค้า หรือยอดขาย",
};
const gapLabels: Record<string, string> = { "การตั้งค่า Key event": "การตั้งค่าเหตุการณ์สำคัญ", "กิจกรรม CI / FHC / LINE": "กิจกรรมเครื่องมือวางแผนและ LINE" };
const gapSteps: Record<string, string> = {
  "ค่าโฆษณาจริง": "เชื่อมรายงานค่าโฆษณาที่มีรหัสแคมเปญและโฆษณา สกุลเงิน และช่วงเวลาที่นับผล ต้นทุนต่อคลิกของคำค้นไม่ใช่ค่าโฆษณาจริง",
  "ลูกค้าที่มีคุณภาพ": "เชื่อมข้อมูลลูกค้าที่ระบุคนหรือรายการติดต่อได้และมีสถานะคัดกรอง การคลิก LINE ยังไม่ยืนยันว่าเป็นลูกค้าที่ผ่านการคัดกรอง",
  "รายได้จริง": "เชื่อมรายได้ที่ระบุแหล่งที่มา วันที่ และสกุลเงิน ก่อนคำนวณผลตอบแทนโฆษณา",
  "การตั้งค่า Key event": "ตรวจใน Google Analytics ว่ากิจกรรมใดถูกตั้งเป็นเหตุการณ์สำคัญ ค่า 0 ยังไม่ยืนยันว่าไม่มีการติดต่อ",
  "แคมเปญและหน้าเข้า": "ดูช่องทาง แคมเปญ และหน้าเข้าในแต่ละแถว หากต้นทางแสดงว่าไม่ได้ระบุ ระบบจะไม่เดาว่าเป็นการเข้าชมโดยตรง",
  "กิจกรรม CI / FHC / LINE": "จำนวนกิจกรรมอาจนับคนเดิมซ้ำ จึงยังคำนวณอัตราหลุดระหว่างขั้นหรือจำนวนลูกค้าไม่ได้",
  "ช่วงเวลาและขอบเขต": "ตรวจวันที่และเขตเวลาของแต่ละรายงาน ห้ามนำคลิกจาก Google Search Console กับเซสชันจาก Google Analytics มาคำนวณเป็นขั้นตอนเดียวกัน",
};
export function PerformanceInsights({ datasets }: { datasets: AnalyticsDataset[] }) {
  const tables = buildPerformanceTables(datasets), seo = tables[0]!, gaps = tables[1]!;
  return <section className="mt-8 min-w-0 border-t border-white/15 pt-6" aria-labelledby="performance-insights-heading">
    <h2 id="performance-insights-heading" className="text-xl font-semibold">เอาข้อมูลไปทำอะไรต่อ</h2>
    <p className="mt-2 max-w-3xl text-sm leading-6 text-white/70">เริ่มจากงานตรวจคำค้นและหน้าเป้าหมาย แล้วดูแคมเปญกับกิจกรรมที่เกิดบนเว็บ แยกไฟล์ตามเรื่องเพื่อจัดตารางวิเคราะห์ต่อได้ Excel รวมชีตวิเคราะห์ไว้ด้วย</p>
    <div className="mt-4 flex flex-wrap gap-3">{tables.filter(table => table.rows.length).map(table => <a download key={table.view} className={link} href={`/api/admin/analytics/export/?view=${table.view}&format=csv`}>CSV · {table.title}</a>)}</div>
    <h3 className="mt-6 font-semibold">งานตรวจ SEO · {seo.rows.length.toLocaleString("th-TH")} รายการ</h3>
    <p className="mt-2 text-sm leading-6 text-white/65">{guidance[seo.view]} เป็นข้อเสนอให้ตรวจงาน ไม่ใช่การรับประกันอันดับหรือยอดขาย</p>
    <details className="mt-2 text-xs text-white/60"><summary className="cursor-pointer">ข้อความต้นฉบับสำหรับทีมดูแล</summary>{seo.guidance}</details>
    {seo.rows.length ? <div className="mt-4 max-w-full overflow-x-auto" tabIndex={0} role="region" aria-label="ตารางงานตรวจ SEO เลื่อนแนวนอนได้"><table className="w-full min-w-[720px] text-left text-sm"><caption className="pb-3 text-left text-xs text-white/60">แสดง {Math.min(10, seo.rows.length)} รายการแรก · CSV มีครบทุกแถว · วันที่ของ Google และ Ubersuggest แยกกัน</caption><thead><tr className="border-b border-white/20">{["คำค้น / หน้า", "งานที่ควรตรวจ", "หลักฐาน Google", "บริบท Ubersuggest"].map(title => <th key={title} scope="col" className="p-3 font-medium text-[#e0c985]">{title}</th>)}</tr></thead><tbody>{seo.rows.slice(0, 10).map((row, index) => <tr key={index} className="border-b border-white/10 align-top"><th scope="row" className="max-w-60 break-words p-3 font-medium">{text(row["คำค้น"])}<span className="mt-1 block text-xs font-normal text-white/60">{text(row["หน้าเป้าหมาย"])}</span></th><td className="max-w-60 p-3">{text(row["งานที่ควรตรวจ"])}<p className="mt-1 text-xs leading-5 text-white/60">{reason(row["เหตุผล / กติกา"])}</p><details className="mt-1 text-xs text-white/60"><summary className="cursor-pointer">ข้อความต้นฉบับสำหรับทีมดูแล</summary>{text(row["เหตุผล / กติกา"])}</details></td><td className="p-3 text-xs leading-5">แสดงผล: {text(row["การแสดงผล GSC"])}<br />คลิก: {text(row["คลิก GSC"])}<br />อันดับเฉลี่ย: {text(row["อันดับเฉลี่ย GSC"])}<br />{row["แหล่งข้อมูล"] === "gsc" ? `ถึง ${text(row["ข้อมูลต้นทาง ณ"])}` : "ยังไม่มีคำค้น GSC"}</td><td className="p-3 text-xs leading-5">เจตนาค้นหา: {intent(row["Intent Ubersuggest"])}<br />ปริมาณค้นหาโดยประมาณ: {text(row["Volume Ubersuggest"])}<br />อันดับต้นทาง: {text(row["อันดับ Ubersuggest"])}<br />ต้นทาง ณ {text(row["Ubersuggest ต้นทาง ณ"])}<details className="mt-1 text-white/60"><summary className="cursor-pointer">เจตนาค้นหาต้นฉบับ</summary>{text(row["Intent Ubersuggest"])}</details></td></tr>)}</tbody></table></div> : <p className="mt-3 text-sm text-white/60">ยังไม่มีรายงานคำค้นที่บันทึกไว้สำหรับเตรียมงาน SEO</p>}
    <details className="mt-6 border-y border-white/15 py-4" open><summary className="cursor-pointer font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#e0c985]">ก่อนวิเคราะห์งบและผลธุรกิจ ยังต้องมีอะไร</summary><p className="mt-3 text-sm leading-6 text-white/70">{guidance[gaps.view]}</p><dl className="mt-3 grid gap-4 sm:grid-cols-2">{gaps.rows.map(row => <div key={String(row["ข้อมูล"])} className="min-w-0"><dt className="font-medium">{gapLabels[String(row["ข้อมูล"])] ?? text(row["ข้อมูล"])}</dt><dd className="mt-1 text-xs leading-5 text-white/65"><span className="text-[#e0c985]">{text(row["สถานะ"])}</span><br />{gapSteps[String(row["ข้อมูล"])] ?? "ขั้นตอนนี้ยังไม่มีคำอธิบายภาษาไทย กรุณาให้ทีมดูแลตรวจข้อมูลต้นฉบับ"}</dd></div>)}</dl><details className="mt-4 text-xs text-white/60"><summary className="cursor-pointer">ข้อความต้นฉบับสำหรับทีมดูแล</summary><p>{gaps.guidance}</p><ul className="mt-2 space-y-1">{gaps.rows.map(row => <li key={String(row["ข้อมูล"])}>{text(row["ข้อมูล"])}: {text(row["ขั้นตอนต่อไป"])}</li>)}</ul></details></details>
    {tables.slice(2).filter(table => table.rows.length).map(table => <div key={table.view} className="mt-3 text-sm leading-6 text-white/65"><strong className="font-medium text-white">{table.title}: </strong>{guidance[table.view] ?? "มีคำอธิบายที่ยังไม่ได้แปล กรุณาให้ทีมดูแลตรวจข้อมูลต้นฉบับ"}<details className="mt-1 text-xs"><summary className="cursor-pointer">ข้อความต้นฉบับสำหรับทีมดูแล</summary>{table.guidance}</details></div>)}
  </section>;
}
