import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { neon } from "@neondatabase/serverless";
import { z } from "zod";
import { MARKETING_ANALYSIS_VERSION, marketingEvidenceSchema, marketingSnapshotSchema, marketingAnalysisInputSchema, marketingAnalysisOutputSchema, buildMarketingInferenceRequest, parseMarketingInterpretation, type MarketingAnalysisInput, type MarketingAnalysisOutput } from "@/lib/local-ai/contracts";
import { createLocalAiPayloadCrypto, createLocalAiRequestFingerprint } from "@/lib/local-ai/crypto";
import { resolveLocalAiAdminRuntime, LOCAL_AI_MIGRATION_CHECKSUM } from "../local-ai/foundation";
import { readMarketingDashboard } from "./store";
import { marketingWindowSchema, type MarketingDashboard, type MarketingWindow, type MarketingMetric } from "./model";
const digest=(v:string)=>createHash("sha256").update(v).digest("hex");
export const MARKETING_ANALYSIS_MIGRATION_VERSION="20260927_marketing_local_analysis_v2";
export const MARKETING_ANALYSIS_MIGRATION_CHECKSUM="sha256:eb0d7a8a1637ccde4bc17d5bc60952da831aec8736123eb42970c467e5306f30";
export const MARKETING_RETRY_MIGRATION_VERSION="20260927_marketing_retry_v3";
export const MARKETING_RETRY_MIGRATION_CHECKSUM="sha256:e150ce6f3fecd22ff312fe5265340eb882b53044c1e6b319f5b6b6aa833a480e";
export const MARKETING_AI_REPAIR_MIGRATION_VERSION="20260928_marketing_ai_repair_retry_v4";
export const MARKETING_AI_REPAIR_MIGRATION_CHECKSUM="sha256:41fc1d9c3fc1ea8487dbe68b5f97fccb292675766d9f38a4281f57f9d7e8f176";
export type MarketingAnalysisRecord={analysisId:string;jobId:string|null;status:"prepared"|"queued"|"running"|"ready"|"failed"|"stale";promptVersion:typeof MARKETING_ANALYSIS_VERSION;analysisType:string;period:MarketingAnalysisInput["period"];createdAt:string;completedAt:string|null;modelName:string|null;inputHash:string;output:MarketingAnalysisOutput|null;sourceManifest:MarketingDashboard["manifest"]};
export type MarketingAnalysisView={state:"ready"|"unavailable";latest:MarketingAnalysisRecord|null;lastGood:MarketingAnalysisRecord|null};
export function buildMarketingAnalysisInput(data:MarketingDashboard):MarketingAnalysisInput{
 if(data.state!=="ready"||data.window.currentEnd<data.window.currentStart)throw new Error("MARKETING_FACTS_UNAVAILABLE");
 const freshness=(metric:string):"fresh"|"expected_lag"|"stale"|"failed"|"unknown"=>data.health.find(h=>h.report===(metric==="organic_sessions"?"ga4-daily-organic":metric.startsWith("search_")?"gsc-daily-page":metric.startsWith("social_")?"social-performance":"ga4-content-events"))?.status??"unknown";
 const evidence:MarketingAnalysisInput["evidence"]=[];
 const safeLabel=(value:string,kind:string)=>{const normalized=value.replace(/\?/g,"").slice(0,160);return !/^[0-9_-]{10,}$/.test(normalized.split(" · ")[0]!)&&marketingEvidenceSchema.shape.label.safeParse(normalized).success?normalized:kind==="content"?"Supplied content asset · metadata label omitted for privacy":"Supplied factual evidence · metadata label omitted for privacy";};
 const add=(kind:"kpi"|"content"|"action"|"health",assetId:string|null,label:string,m:MarketingMetric,measurementStatus:string|null=null)=>{evidence.push({id:`e${evidence.length+1}`,kind,assetId,label:safeLabel(label,kind),metric:m.metric,current:m.current,previous:m.previous,absoluteChange:m.absoluteChange,percentageChange:m.percentageChange,sampleStatus:m.sampleStatus,coverageStatus:m.coverageStatus,freshnessStatus:freshness(m.metric),evidenceRef:m.evidenceRef,measurementStatus});};
 for(const m of [...data.kpis].sort((a,b)=>["line_clicks","calculator_complete","organic_sessions","search_clicks","search_impressions"].indexOf(a.metric)-["line_clicks","calculator_complete","organic_sessions","search_clicks","search_impressions"].indexOf(b.metric)))add("kpi",null,m.metric,m);
 for(const id of ["growing","declining","organic_sessions","search_clicks","social_facebook","social_instagram"]){const row=data.leaderboards.find(b=>b.id===id)?.rows[0];if(row&&!evidence.some(e=>e.assetId===row.assetId&&e.metric===row.metric))add("content",row.assetId,`${row.title} · ${row.category??"uncategorized"}`,row);}
 for(const a of data.actions.filter(a=>a.executedAt).slice(0,2))add("action",a.assetId,`Observed action · ${a.actionType}`,{metric:a.expectedMetric,current:a.result,previous:a.baseline,absoluteChange:a.absoluteChange,percentageChange:a.percentageChange,sampleStatus:a.measurementStatus==="covered_pre_post_observation_not_causality"&&a.baseline!==null&&a.result!==null&&a.baseline>=(data.kpis.find(m=>m.metric===a.expectedMetric)?.threshold??Number.POSITIVE_INFINITY)&&a.result>=(data.kpis.find(m=>m.metric===a.expectedMetric)?.threshold??Number.POSITIVE_INFINITY)?"sufficient":"insufficient_data",coverageStatus:a.measurementStatus==="covered_pre_post_observation_not_causality"?"complete":"insufficient_history",freshnessStatus:"unknown",threshold:0,unit:"native",evidenceRef:`action:${a.id}`},a.measurementStatus);
 const pool=evidence.length;
 const groups=["kpi","content","action"] as const;
 const selected:MarketingAnalysisInput["evidence"]=[];
 const pools=groups.map(kind=>evidence.filter(e=>e.kind===kind).sort((a,b)=>Number(b.sampleStatus==="sufficient")-Number(a.sampleStatus==="sufficient")));
 for(let i=0;selected.length<16;i++){let added=false;for(const group of pools){if(group[i]&&selected.length<16){selected.push(group[i]!);added=true;}}if(!added)break;}
 const manifest=data.manifest;
 const sourceManifestHash=digest(JSON.stringify(manifest));
 const make=()=>{const snapshot=marketingSnapshotSchema.parse({promptVersion:MARKETING_ANALYSIS_VERSION,analysisType:data.window.key.includes("month")||data.window.key==="rolling_28"?"monthly_performance":"weekly_performance",definitionVersions:{analytics:"marketing-v2",rules:"marketing-rules-v1",identity:"marketing-identity-v1",freshness:"marketing-calendar-v2"},period:data.window,sourceManifest:[],sourceManifestHash,evidence:selected,coverage:{prepared:pool,sent:selected.length,dropped:pool-selected.length},limitations:["Qualified conversations, spend and attributed revenue are unavailable", "Events are repeatable behavioral activity, not confirmed leads or a cohort funnel", "Social metrics are native snapshots, not activity during the selected period", "Before/after is observational, not causality; human fields are excluded", "Only bounded supplied evidence is interpreted; deterministic leaderboards retain their order", "Unsafe metadata labels are omitted; exact content identities and metric references remain server-side"]});return marketingAnalysisInputSchema.parse({...snapshot,snapshotHash:digest(JSON.stringify(snapshot))});};
 let result=make();while(buildMarketingInferenceRequest(result).promptBytes>6000||Buffer.byteLength(JSON.stringify(result))>20000){if(selected.length<=1)throw new Error("MARKETING_CONTEXT_BUDGET_EXCEEDED");selected.pop();result=make();}return result;
}
async function client(requireRepairProfile=false){const runtime=resolveLocalAiAdminRuntime();if(!runtime||!process.env.CCPUN_ADMIN_DATABASE_URL?.trim())throw new Error("MARKETING_AI_NOT_CONFIGURED");const sql=neon(process.env.CCPUN_ADMIN_DATABASE_URL.trim(),{fetchOptions:{signal:AbortSignal.timeout(10000)}});const rows=await sql.query("SELECT current_database()='neondb' AND current_user=$1 AND EXISTS(SELECT 1 FROM ccpun_admin.local_ai_identity WHERE singleton AND lane=$2 AND project_id=$3 AND branch_id=$4 AND endpoint_id=$5 AND migration_checksum=$6) AND EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version=$7 AND checksum=$8) AND EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version=$9 AND checksum=$10) AND (NOT $11::boolean OR EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version=$12 AND checksum=$13)) AS ready",[runtime.localAiIdentity.runtimeRole,runtime.lane,runtime.localAiIdentity.projectId,runtime.localAiIdentity.branchId,runtime.localAiIdentity.endpointId,LOCAL_AI_MIGRATION_CHECKSUM,MARKETING_ANALYSIS_MIGRATION_VERSION,MARKETING_ANALYSIS_MIGRATION_CHECKSUM,MARKETING_RETRY_MIGRATION_VERSION,MARKETING_RETRY_MIGRATION_CHECKSUM,requireRepairProfile,MARKETING_AI_REPAIR_MIGRATION_VERSION,MARKETING_AI_REPAIR_MIGRATION_CHECKSUM]);if(rows[0]?.ready!==true)throw new Error("MARKETING_AI_NOT_CONFIGURED");return sql;}
export async function prepareMarketingAnalysis(window:MarketingWindow="this_week"){const data=await readMarketingDashboard(marketingWindowSchema.parse(window));if(data.state==="ready"&&data.window.currentEnd<data.window.currentStart)return{status:"waiting",reason:"expected-provider-lag",factsRemainAvailable:true};const input=buildMarketingAnalysisInput(data);const hash=createLocalAiRequestFingerprint("marketing-analysis",input);const rows=await(await client()).query("SELECT ccpun_admin.admin_prepare_marketing_analysis($1::uuid,$2::jsonb,$3,$4::jsonb) AS data",[randomUUID(),JSON.stringify(input),hash,JSON.stringify(data.manifest)]);return rows[0]?.data;}
export async function enqueueMarketingAnalysis(analysisId:string,inputHash:string){const sql=await client(true);const rows=await sql.query("SELECT ccpun_admin.admin_marketing_analysis_input($1::uuid,$2) AS data",[z.string().uuid().parse(analysisId),z.string().regex(/^[a-f0-9]{64}$/).parse(inputHash)]);const input=marketingAnalysisInputSchema.parse(rows[0]?.data);const jobId=randomUUID(),encrypted=createLocalAiPayloadCrypto().encrypt(jobId,"marketing-analysis",input);const result=await sql.query("SELECT ccpun_admin.admin_enqueue_marketing_analysis($1::uuid,$2::uuid,$3,$4,$5,$6::smallint,$7,$8) AS data",[analysisId,jobId,encrypted.ciphertextB64,encrypted.nonceB64,encrypted.authTagB64,encrypted.keyVersion,inputHash,digest(jobId+":marketing-n8n-service")]);return result[0]?.data;}
export async function readMarketingAnalysis(window:MarketingWindow="this_week"):Promise<MarketingAnalysisView>{try{const rows=await(await client()).query("SELECT ccpun_admin.admin_read_marketing_analysis($1) AS data",[marketingWindowSchema.parse(window)]);const data=rows[0]?.data;if(!data||!(data.latest===null||typeof data.latest==="object"))throw new Error("MARKETING_AI_RESPONSE_INVALID");for(const record of [data.latest,data.lastGood])if(record?.output)record.output=marketingAnalysisOutputSchema.parse(record.output);return{state:"ready",...data};}catch{return{state:"unavailable",latest:null,lastGood:null};}}
export async function marketingAnalysisStatus(analysisId:string){const rows=await(await client(true)).query("SELECT ccpun_admin.admin_marketing_analysis_status($1::uuid) AS data",[z.string().uuid().parse(analysisId)]);return rows[0]?.data;}
export async function validateMarketingAnalysis(analysisId:string){const sql=await client();const row=(await sql.query("SELECT ccpun_admin.admin_marketing_analysis_validation_input($1::uuid) AS data",[z.string().uuid().parse(analysisId)]))[0]?.data;if(!row)return{status:"not-ready",analysisId};try{assertMarketingAnalysisGrounded(row.input,row.output);}catch{const failed=await sql.query("SELECT ccpun_admin.admin_reject_marketing_analysis($1::uuid,$2) AS data",[analysisId,row.outputDigest]);return failed[0]?.data;}
 const rows=await sql.query("SELECT ccpun_admin.admin_validate_marketing_analysis($1::uuid,$2) AS data",[analysisId,row.outputDigest]);return rows[0]?.data;
}

export function assertMarketingAnalysisGrounded(inputValue:unknown,outputValue:unknown){const input=marketingAnalysisInputSchema.parse(inputValue);const output=marketingAnalysisOutputSchema.parse(outputValue);const findings=[...output.wins,...output.risks,...output.opportunities,...output.watchItems].sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));if(findings.length>3||new Set(findings.map(i=>i.id)).size!==findings.length)throw new Error("MARKETING_OUTPUT_GROUNDING_REJECTED");const insights=findings.map(i=>({type:i.type,evidenceIds:i.evidence.map(e=>e.id),explanation:i.explanation,action:i.action,priority:i.priority,confidence:i.confidence}));
 const result=parseMarketingInterpretation(input,{summary:output.summary,insights,dataQualityNotes:output.dataQualityNotes,reviewRequired:true});if(!result.success||createLocalAiRequestFingerprint("marketing-analysis",output)!==createLocalAiRequestFingerprint("marketing-analysis",result.data))throw new Error("MARKETING_OUTPUT_GROUNDING_REJECTED");for(const i of [...output.wins,...output.risks,...output.opportunities,...output.watchItems,...output.recommendedActions])for(const e of i.evidence){const supplied=input.evidence.find(x=>x.id===e.id);if(JSON.stringify(e)!==JSON.stringify(supplied))throw new Error("MARKETING_OUTPUT_FACTS_CHANGED");}}

export async function captureMarketingMeasurements(){const rows=await(await client()).query("SELECT ccpun_admin.admin_capture_marketing_measurements() AS data",[]);return rows[0]?.data;}
