import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { neon } from "@neondatabase/serverless";
import { z } from "zod";
import { MARKETING_ANALYSIS_VERSION, marketingEvidenceSchema, marketingSnapshotSchema, marketingAnalysisInputSchema, marketingAnalysisOutputSchema, buildMarketingInferenceRequest, parseMarketingInterpretation, type MarketingAnalysisInput, type MarketingAnalysisOutput, type MarketingCandidate, marketingV2RequiresSelection, marketingV2SelectionSchema } from "@/lib/local-ai/contracts";
import { createLocalAiPayloadCrypto, createLocalAiRequestFingerprint } from "@/lib/local-ai/crypto";
import { resolveLocalAiAdminRuntime, LOCAL_AI_MIGRATION_CHECKSUM } from "../local-ai/foundation";
import { readMarketingDashboard } from "./store";
import { marketingMetricLabels, marketingWindowSchema, type MarketingDashboard, type MarketingWindow, type MarketingMetric } from "./model";
const digest=(v:string)=>createHash("sha256").update(v).digest("hex");
export const MARKETING_ANALYSIS_MIGRATION_VERSION="20260927_marketing_local_analysis_v2";
export const MARKETING_ANALYSIS_MIGRATION_CHECKSUM="sha256:eb0d7a8a1637ccde4bc17d5bc60952da831aec8736123eb42970c467e5306f30";
export const MARKETING_RETRY_MIGRATION_VERSION="20260927_marketing_retry_v3";
export const MARKETING_RETRY_MIGRATION_CHECKSUM="sha256:e150ce6f3fecd22ff312fe5265340eb882b53044c1e6b319f5b6b6aa833a480e";
export const MARKETING_AI_REPAIR_MIGRATION_VERSION="20260928_marketing_ai_repair_retry_v4";
export const MARKETING_AI_REPAIR_MIGRATION_CHECKSUM="sha256:27d012741dd64bbb1d5378ecb4bcd165a9e379b8046342d13019d2dec67290db";
export const MARKETING_CLOUD_MIGRATION_VERSION="20260928_marketing_cloud_fallback_v1";
export const MARKETING_CLOUD_MIGRATION_CHECKSUM="sha256:c582ea59bffd69322fe3fe07922c2681b12b019cff7921a9735bbf5a03ae0ad3";
export const MARKETING_CLOUD_PROMPT_MIGRATION_VERSION="20260928_marketing_cloud_prompt_v2";
export const MARKETING_CLOUD_PROMPT_MIGRATION_CHECKSUM="sha256:0fdd5ea1ac71e1de301536336eead7cc839973a0c3f8492dd10651226a79ee7c";
export const MARKETING_CLOUD_TIMEOUT_MIGRATION_VERSION="20260928_marketing_cloud_timeout_v3";
export const MARKETING_CLOUD_TIMEOUT_MIGRATION_CHECKSUM="sha256:d37f6baf16ef77b21c05a664d77dd6cd7427b74de60d1cf7557ee581da6ff5f0";
export const MARKETING_AI_CANDIDATES_MIGRATION_VERSION="20260928_marketing_ai_candidates_v5";
export const MARKETING_AI_CANDIDATES_MIGRATION_CHECKSUM="sha256:44eb2289295711409d4b28b97de58112c36b4d63b070cf6ada147c040a747f8b";
export const MARKETING_CLOUD_PROMPT_VERSION="marketing-performance-cloud-v1";
export const MARKETING_CLOUD_PROMPT_VERSION_V2="marketing-performance-cloud-v2";
const MARKETING_CLOUD_GUARDS="Do not use learning without a supplied mature action measurement. Do not mention content without a supplied content fact. Avoid the Thai phrase ยืนยันว่า even when negated. When previous or change is null, avoid Thai words implying direction even when negated, including เพิ่มขึ้น ลดลง สูงขึ้น and เติบโต.";
export type MarketingAnalysisRecord={analysisId:string;jobId:string|null;status:"prepared"|"queued"|"running"|"ready"|"failed"|"stale";promptVersion:MarketingAnalysisInput["promptVersion"];analysisType:string;period:MarketingAnalysisInput["period"];createdAt:string;completedAt:string|null;modelName:string|null;inferenceProvider?:"local"|"openai"|null;cloudUsage?:{inputTokens:number;outputTokens:number}|null;inputHash:string;output:MarketingAnalysisOutput|null;sourceManifest:MarketingDashboard["manifest"]};
export type MarketingAnalysisView={state:"ready"|"unavailable";latest:MarketingAnalysisRecord|null;lastGood:MarketingAnalysisRecord|null};
export function buildMarketingAnalysisInput(data:MarketingDashboard):MarketingAnalysisInput{
 if(data.state!=="ready"||data.window.currentEnd<data.window.currentStart)throw new Error("MARKETING_FACTS_UNAVAILABLE");
 const freshness=(metric:string):"fresh"|"expected_lag"|"stale"|"failed"|"unknown"=>data.health.find(h=>h.report===(metric==="organic_sessions"?"ga4-daily-organic":metric.startsWith("search_")?"gsc-daily-page":metric.startsWith("social_")?"social-performance":"ga4-content-events"))?.status??"unknown";
 const evidence:MarketingAnalysisInput["evidence"]=[];
 const safeLabel=(value:string,kind:string)=>{const normalized=value.replace(/\?/g,"").slice(0,160);return !/^[0-9_-]{10,}$/.test(normalized.split(" · ")[0]!)&&marketingEvidenceSchema.shape.label.safeParse(normalized).success?normalized:kind==="content"?"เนื้อหาในระบบที่ซ่อนชื่อเพื่อความปลอดภัย":"ข้อมูลในระบบที่ซ่อนชื่อเพื่อความปลอดภัย";};
 const add=(kind:"kpi"|"content"|"action"|"health",assetId:string|null,label:string,m:MarketingMetric,measurementStatus:string|null=null)=>{evidence.push({id:`e${evidence.length+1}`,kind,assetId,label:safeLabel(label,kind),metric:m.metric,current:m.current,previous:m.previous,absoluteChange:m.absoluteChange,percentageChange:m.percentageChange,sampleStatus:m.sampleStatus,coverageStatus:m.coverageStatus,freshnessStatus:freshness(m.metric),evidenceRef:m.evidenceRef,measurementStatus});};
 for(const m of [...data.kpis].sort((a,b)=>["line_clicks","calculator_complete","organic_sessions","search_clicks","search_impressions"].indexOf(a.metric)-["line_clicks","calculator_complete","organic_sessions","search_clicks","search_impressions"].indexOf(b.metric)))add("kpi",null,marketingMetricLabels[m.metric]??m.metric,m);
 for(const id of ["growing","declining","organic_sessions","search_clicks","social_facebook","social_instagram"]){const row=data.leaderboards.find(b=>b.id===id)?.rows[0];if(row&&!evidence.some(e=>e.assetId===row.assetId&&e.metric===row.metric))add("content",row.assetId,`${row.title} · ${row.category??"uncategorized"}`,row);}
 for(const a of data.actions.filter(a=>a.executedAt).slice(0,2))add("action",a.assetId,`Observed action · ${a.actionType}`,{metric:a.expectedMetric,current:a.result,previous:a.baseline,absoluteChange:a.absoluteChange,percentageChange:a.percentageChange,sampleStatus:a.measurementStatus==="covered_pre_post_observation_not_causality"&&a.baseline!==null&&a.result!==null&&a.baseline>=(data.kpis.find(m=>m.metric===a.expectedMetric)?.threshold??Number.POSITIVE_INFINITY)&&a.result>=(data.kpis.find(m=>m.metric===a.expectedMetric)?.threshold??Number.POSITIVE_INFINITY)?"sufficient":"insufficient_data",coverageStatus:a.measurementStatus==="covered_pre_post_observation_not_causality"?"complete":"insufficient_history",freshnessStatus:"unknown",threshold:0,unit:"native",evidenceRef:`action:${a.id}`},a.measurementStatus);
 for(const h of data.health.filter(h=>["stale","failed"].includes(h.status)).slice(0,4))evidence.push({id:`e${evidence.length+1}`,kind:"health",assetId:null,label:safeLabel(`ความพร้อมข้อมูลจาก ${h.source}`,"health"),metric:"source_health",current:null,previous:null,absoluteChange:null,percentageChange:null,sampleStatus:"insufficient_data",coverageStatus:"partial",freshnessStatus:h.status,evidenceRef:`health:${h.report}`,measurementStatus:null});
 const pool=evidence.length;
 // ponytail: a native social snapshot without a prior value cannot support a trend claim; keep it in factual views.
 const comparableEvidence=evidence.filter(e=>!(e.metric.startsWith("social_")&&e.previous===null));
 const groups=["kpi","content","action","health"] as const;
 const selected:MarketingAnalysisInput["evidence"]=[];
 const pools=groups.map(kind=>comparableEvidence.filter(e=>e.kind===kind).sort((a,b)=>Number(b.sampleStatus==="sufficient")-Number(a.sampleStatus==="sufficient")));
 for(let i=0;selected.length<16;i++){let added=false;for(const group of pools){if(group[i]&&selected.length<16){selected.push(group[i]!);added=true;}}if(!added)break;}
 const manifest=data.manifest;
 const sourceManifestHash=digest(JSON.stringify(manifest));
 const make=()=>{const candidates:MarketingCandidate[]=data.opportunities.slice().sort((a,b)=>({high:0,medium:1,low:2}[a.priority]-{high:0,medium:1,low:2}[b.priority])||a.id.localeCompare(b.id)).slice(0,32).flatMap((o,index)=>{if(!["performance","data_health"].includes(o.area)||!o.evidenceRefs.length||o.evidenceRefs.length>3||!o.evidenceRefs.every(ref=>selected.some(e=>e.evidenceRef===ref)))return[];const refs=o.evidenceRefs.map(ref=>selected.find(e=>e.evidenceRef===ref)!);if(o.area==="performance"&&refs.some(e=>e.sampleStatus!=="sufficient"||e.coverageStatus!=="complete"||e.current===null||e.previous===null||e.current>=e.previous))return[];if(o.area==="data_health"&&refs.some(e=>!["stale","failed"].includes(e.freshnessStatus)))return[];const action=o.recommendedAction==="investigation"?"investigation" as const:"monitor" as const;return[{id:`c${index+1}`,opportunityId:o.id,area:o.area as "performance"|"data_health",evidenceIds:refs.map(e=>e.id),action,priority:o.priority,confidence:refs.some(e=>e.sampleStatus!=="sufficient"||e.coverageStatus!=="complete"||!["fresh","expected_lag"].includes(e.freshnessStatus))?"low" as const:o.confidence,explanation:o.area==="performance"?`ข้อมูล${refs[0]!.label}ลดลงในช่วงที่เปรียบเทียบได้ ควรตรวจสอบสาเหตุ`:"ข้อมูลจากแหล่งนี้ล่าช้าหรือดึงไม่สำเร็จ ควรตรวจระบบก่อนใช้วิเคราะห์"}];}).slice(0,8);const snapshot=marketingSnapshotSchema.parse({promptVersion:MARKETING_ANALYSIS_VERSION,candidates,analysisType:data.window.key.includes("month")||data.window.key==="rolling_28"?"monthly_performance":"weekly_performance",definitionVersions:{analytics:"marketing-v2",rules:"marketing-rules-v1",identity:"marketing-identity-v1",freshness:"marketing-calendar-v2"},period:data.window,sourceManifest:[],sourceManifestHash,evidence:selected,coverage:{prepared:pool,sent:selected.length,dropped:pool-selected.length},limitations:["Qualified conversations, spend and attributed revenue are unavailable", "Events are repeatable behavioral activity, not confirmed leads or a cohort funnel", "Social metrics are native snapshots; omit them from AI trend evidence until a comparable prior snapshot exists", "Before/after is observational, not causality; human fields are excluded", "Only bounded supplied evidence is interpreted; deterministic leaderboards retain their order", "Unsafe metadata labels are omitted; exact content identities and metric references remain server-side"]});return marketingAnalysisInputSchema.parse({...snapshot,snapshotHash:digest(JSON.stringify(snapshot))});};
 let result=make();while(buildMarketingInferenceRequest(result).promptBytes>6000||Buffer.byteLength(JSON.stringify(result))>20000){if(selected.length<=1)throw new Error("MARKETING_CONTEXT_BUDGET_EXCEEDED");selected.pop();result=make();}return result;
}
async function client(requireRepairProfile=false,requireCloud=false,requireV2=false){const runtime=resolveLocalAiAdminRuntime();if(!runtime||!process.env.CCPUN_ADMIN_DATABASE_URL?.trim())throw new Error("MARKETING_AI_NOT_CONFIGURED");const sql=neon(process.env.CCPUN_ADMIN_DATABASE_URL.trim(),{fetchOptions:{signal:AbortSignal.timeout(10000)}});const rows=await sql.query("SELECT current_database()='neondb' AND current_user=$1 AND EXISTS(SELECT 1 FROM ccpun_admin.local_ai_identity WHERE singleton AND lane=$2 AND project_id=$3 AND branch_id=$4 AND endpoint_id=$5 AND migration_checksum=$6) AND EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version=$7 AND checksum=$8) AND EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version=$9 AND checksum=$10) AND (NOT $11::boolean OR EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version=$12 AND checksum=$13)) AND (NOT $14::boolean OR (EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version=$15 AND checksum=$16) AND EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version=$17 AND checksum=$18) AND EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version=$19 AND checksum=$20))) AS ready",[runtime.localAiIdentity.runtimeRole,runtime.lane,runtime.localAiIdentity.projectId,runtime.localAiIdentity.branchId,runtime.localAiIdentity.endpointId,LOCAL_AI_MIGRATION_CHECKSUM,MARKETING_ANALYSIS_MIGRATION_VERSION,MARKETING_ANALYSIS_MIGRATION_CHECKSUM,MARKETING_RETRY_MIGRATION_VERSION,MARKETING_RETRY_MIGRATION_CHECKSUM,requireRepairProfile,MARKETING_AI_REPAIR_MIGRATION_VERSION,MARKETING_AI_REPAIR_MIGRATION_CHECKSUM,requireCloud,MARKETING_CLOUD_MIGRATION_VERSION,MARKETING_CLOUD_MIGRATION_CHECKSUM,MARKETING_CLOUD_PROMPT_MIGRATION_VERSION,MARKETING_CLOUD_PROMPT_MIGRATION_CHECKSUM,MARKETING_CLOUD_TIMEOUT_MIGRATION_VERSION,MARKETING_CLOUD_TIMEOUT_MIGRATION_CHECKSUM]);if(rows[0]?.ready!==true)throw new Error("MARKETING_AI_NOT_CONFIGURED");if(requireV2){const check=await sql.query("SELECT EXISTS(SELECT 1 FROM ccpun_admin.schema_migration WHERE version=$1 AND checksum=$2) AS ready",[MARKETING_AI_CANDIDATES_MIGRATION_VERSION,MARKETING_AI_CANDIDATES_MIGRATION_CHECKSUM]);if(check[0]?.ready!==true)throw new Error("MARKETING_AI_V2_NOT_CONFIGURED");}return sql;}
export async function prepareMarketingAnalysis(window:MarketingWindow="this_week"){const data=await readMarketingDashboard(marketingWindowSchema.parse(window));if(data.state==="ready"&&data.window.currentEnd<data.window.currentStart)return{status:"waiting",reason:"expected-provider-lag",factsRemainAvailable:true};const input=buildMarketingAnalysisInput(data);const hash=createLocalAiRequestFingerprint("marketing-analysis",input);const rows=await(await client(false,false,true)).query("SELECT ccpun_admin.admin_prepare_marketing_analysis($1::uuid,$2::jsonb,$3,$4::jsonb) AS data",[randomUUID(),JSON.stringify(input),hash,JSON.stringify(data.manifest)]);return rows[0]?.data;}
export async function enqueueMarketingAnalysis(analysisId:string,inputHash:string){const sql=await client(true,false,true);const rows=await sql.query("SELECT ccpun_admin.admin_marketing_analysis_input($1::uuid,$2) AS data",[z.string().uuid().parse(analysisId),z.string().regex(/^[a-f0-9]{64}$/).parse(inputHash)]);const input=marketingAnalysisInputSchema.parse(rows[0]?.data);const jobId=randomUUID(),encrypted=createLocalAiPayloadCrypto().encrypt(jobId,"marketing-analysis",input);const result=await sql.query(`SELECT ccpun_admin.${input.promptVersion===MARKETING_ANALYSIS_VERSION?"admin_enqueue_marketing_analysis_v2":"admin_enqueue_marketing_analysis"}($1::uuid,$2::uuid,$3,$4,$5,$6::smallint,$7,$8) AS data`,[analysisId,jobId,encrypted.ciphertextB64,encrypted.nonceB64,encrypted.authTagB64,encrypted.keyVersion,inputHash,digest(jobId+":marketing-n8n-service")]);return result[0]?.data;}
export async function readMarketingAnalysis(window:MarketingWindow="this_week"):Promise<MarketingAnalysisView>{try{const rows=await(await client()).query("SELECT ccpun_admin.admin_read_marketing_analysis($1) AS data",[marketingWindowSchema.parse(window)]);const data=rows[0]?.data;if(!data||!(data.latest===null||typeof data.latest==="object"))throw new Error("MARKETING_AI_RESPONSE_INVALID");for(const record of [data.latest,data.lastGood])if(record?.output)record.output=marketingAnalysisOutputSchema.parse(record.output);return{state:"ready",...data};}catch{return{state:"unavailable",latest:null,lastGood:null};}}
export async function marketingAnalysisStatus(analysisId:string){const rows=await(await client(true)).query("SELECT ccpun_admin.admin_marketing_analysis_status($1::uuid) AS data",[z.string().uuid().parse(analysisId)]);return rows[0]?.data;}
export async function validateMarketingAnalysis(analysisId:string){const sql=await client();const row=(await sql.query("SELECT ccpun_admin.admin_marketing_analysis_validation_input($1::uuid) AS data",[z.string().uuid().parse(analysisId)]))[0]?.data;if(!row)return{status:"not-ready",analysisId};try{assertMarketingAnalysisGrounded(row.input,row.output);}catch{const failed=await sql.query("SELECT ccpun_admin.admin_reject_marketing_analysis($1::uuid,$2) AS data",[analysisId,row.outputDigest]);return failed[0]?.data;}
 const rows=await sql.query("SELECT ccpun_admin.admin_validate_marketing_analysis($1::uuid,$2) AS data",[analysisId,row.outputDigest]);return rows[0]?.data;
}

export function assertMarketingAnalysisGrounded(inputValue:unknown,outputValue:unknown){const input=marketingAnalysisInputSchema.parse(inputValue);const output=marketingAnalysisOutputSchema.parse(outputValue);if(input.promptVersion!==output.promptVersion)throw new Error("MARKETING_OUTPUT_VERSION_MISMATCH");if(input.promptVersion===MARKETING_ANALYSIS_VERSION){const findings=[...output.wins,...output.risks,...output.opportunities,...output.watchItems].sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));const selection=marketingV2SelectionSchema.parse({rankedCandidateIds:findings.map(i=>i.candidateId),reviewRequired:true});const parsed=parseMarketingInterpretation(input,selection);if(!parsed.success||createLocalAiRequestFingerprint("marketing-analysis",parsed.data)!==createLocalAiRequestFingerprint("marketing-analysis",output))throw new Error("MARKETING_OUTPUT_GROUNDING_REJECTED");if(marketingV2RequiresSelection(input)&&!findings.length)throw new Error("MARKETING_SIGNIFICANT_CANDIDATE_OMITTED");return;}const findings=[...output.wins,...output.risks,...output.opportunities,...output.watchItems].sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));if(findings.length>3||new Set(findings.map(i=>i.id)).size!==findings.length)throw new Error("MARKETING_OUTPUT_GROUNDING_REJECTED");const insights=findings.map(i=>({type:i.type,evidenceIds:i.evidence.map(e=>e.id),explanation:i.explanation,action:i.action,priority:i.priority,confidence:i.confidence}));
 const result=parseMarketingInterpretation(input,{summary:output.summary,insights,dataQualityNotes:output.dataQualityNotes,reviewRequired:true});if(!result.success||createLocalAiRequestFingerprint("marketing-analysis",output)!==createLocalAiRequestFingerprint("marketing-analysis",result.data))throw new Error("MARKETING_OUTPUT_GROUNDING_REJECTED");for(const i of [...output.wins,...output.risks,...output.opportunities,...output.watchItems,...output.recommendedActions])for(const e of i.evidence){const supplied=input.evidence.find(x=>x.id===e.id);if(JSON.stringify(e)!==JSON.stringify(supplied))throw new Error("MARKETING_OUTPUT_FACTS_CHANGED");}}

export async function captureMarketingMeasurements(){const rows=await(await client()).query("SELECT ccpun_admin.admin_capture_marketing_measurements() AS data",[]);return rows[0]?.data;}

const cloudIdentity=z.object({analysisId:z.string().uuid(),inputHash:z.string().regex(/^[a-f0-9]{64}$/)});
const cloudUsage=z.object({inputTokens:z.number().int().nonnegative().max(100000),outputTokens:z.number().int().nonnegative().max(100000)}).strict();
// ponytail: Responses strict schema rejects descriptive Zod constraints; server-side Zod/grounding still enforces them.
export function marketingOpenAiStrictSchema(value:unknown):unknown{if(Array.isArray(value))return value.map(marketingOpenAiStrictSchema);if(!value||typeof value!=="object")return value;const source=value as Record<string,unknown>,out:Record<string,unknown>={};for(const [key,item] of Object.entries(source)){if(["$schema","minItems","maxItems","minLength","maxLength","minimum","maximum","pattern","format","default"].includes(key))continue;if(key==="const"){out.enum=[item];continue;}out[key]=marketingOpenAiStrictSchema(item);}if(out.type==="object"&&out.properties&&typeof out.properties==="object"){out.additionalProperties=false;out.required=Object.keys(out.properties);}return out;}
export function buildMarketingCloudRequest(input:MarketingAnalysisInput){const request=buildMarketingInferenceRequest(input),version=input.promptVersion===MARKETING_ANALYSIS_VERSION?MARKETING_CLOUD_PROMPT_VERSION_V2:MARKETING_CLOUD_PROMPT_VERSION;const messages=[{...request.messages[0]!,content:input.promptVersion===MARKETING_ANALYSIS_VERSION?request.messages[0]!.content:`${request.messages[0]!.content} ${MARKETING_CLOUD_GUARDS}`},request.messages[1]!],format=marketingOpenAiStrictSchema(request.format);if(Buffer.byteLength(JSON.stringify({messages,format}))>6500)throw new Error("MARKETING_CLOUD_CONTEXT_BUDGET_EXCEEDED");const cloudPromptDigest=digest(JSON.stringify({version,messages,format}));return{messages,format,cloudPromptDigest,cloudPromptVersion:version};}
export async function reserveMarketingCloudFallback(value:unknown){const {analysisId,inputHash}=cloudIdentity.parse(value);const sql=await client(true,true,true);const input=marketingAnalysisInputSchema.parse((await sql.query("SELECT ccpun_admin.admin_marketing_analysis_input($1::uuid,$2) AS data",[analysisId,inputHash]))[0]?.data);const request=buildMarketingCloudRequest(input);const row=(await sql.query(`SELECT ccpun_admin.${input.promptVersion===MARKETING_ANALYSIS_VERSION?"admin_reserve_marketing_cloud_v3":"admin_reserve_marketing_cloud_v2"}($1::uuid,$2,$3::uuid,$4,$5) AS data`,[analysisId,inputHash,randomUUID(),request.cloudPromptVersion,request.cloudPromptDigest]))[0]?.data;if(row?.status!=="reserved"||row?.reused)return row;return{...row,inputHash,provider:"openai",model:"gpt-6-luna",...request,promptVersion:input.promptVersion,cloudPromptVersion:request.cloudPromptVersion,snapshotHash:input.snapshotHash};}
export async function submitMarketingCloudFallback(value:unknown){const v=z.object({...cloudIdentity.shape,reservationId:z.string().uuid(),selection:z.unknown(),usage:cloudUsage}).parse(value);const sql=await client(true,true,true);const input=marketingAnalysisInputSchema.parse((await sql.query("SELECT ccpun_admin.admin_marketing_analysis_input($1::uuid,$2) AS data",[v.analysisId,v.inputHash]))[0]?.data);let output:MarketingAnalysisOutput;try{const selection=typeof v.selection==="string"?JSON.parse(v.selection):v.selection;const parsed=parseMarketingInterpretation(input,selection);if(!parsed.success)throw new Error("MARKETING_OUTPUT_INVALID");assertMarketingAnalysisGrounded(input,parsed.data);output=parsed.data;}catch{await failMarketingCloudFallback({analysisId:v.analysisId,inputHash:v.inputHash,reservationId:v.reservationId,reason:"model-output-invalid"});return{analysisId:v.analysisId,status:"failed",reason:"model-output-invalid"};}const outputDigest=digest(JSON.stringify(output));return(await sql.query("SELECT ccpun_admin.admin_complete_marketing_cloud($1::uuid,$2,$3::uuid,$4::jsonb,$5,$6::integer,$7::integer) AS data",[v.analysisId,v.inputHash,v.reservationId,JSON.stringify(output),outputDigest,v.usage.inputTokens,v.usage.outputTokens]))[0]?.data;}
export async function failMarketingCloudFallback(value:unknown){const v=z.object({...cloudIdentity.shape,reservationId:z.string().uuid(),reason:z.enum(["api-error","model-output-invalid","timeout","workflow-error"])}).parse(value);return(await(await client(true,true)).query("SELECT ccpun_admin.admin_fail_marketing_cloud($1::uuid,$2,$3::uuid,$4) AS data",[v.analysisId,v.inputHash,v.reservationId,v.reason]))[0]?.data;}
