import "server-only";
import { z } from "zod";
import { fetchGscSearchAnalytics } from "../seo-intelligence/providers/gsc";
import { shiftAnalyticsDate, ga4MarketingRequest, normalizeGa4Marketing, type AnalyticsDataset, type AnalyticsReport } from "../analytics/model";
const definitions = {
  "ga4-daily-organic": { dimensions: ["date", "landingPage"], metrics: ["sessions", "engagedSessions"], columns: ["วันที่", "หน้าเข้า", "เซสชัน", "Engaged sessions"] },
  "ga4-content-events": { dimensions: ["date", "eventName", "pagePath"], metrics: ["eventCount"], columns: ["วันที่", "Event", "หน้าเว็บ", "จำนวน event"] },
} as const;
const responseSchema = z.object({ dimensionHeaders: z.array(z.object({name:z.string()})),metricHeaders:z.array(z.object({name:z.string()})),rows:z.array(z.object({dimensionValues:z.array(z.object({value:z.string()})),metricValues:z.array(z.object({value:z.string()}))})).max(10000).default([]),rowCount:z.number().int().nonnegative().default(0),metadata:z.object({timeZone:z.string().optional(),subjectToThresholding:z.boolean().optional(),dataLossFromOtherRow:z.boolean().optional(),samplingMetadatas:z.array(z.unknown()).optional()}).optional() });
export function normalizeMarketingGa4(report: keyof typeof definitions, raw: unknown, start: string, end: string) {
 const data=responseSchema.parse(raw), d=definitions[report];
 if(data.dimensionHeaders.map(x=>x.name).join()!==d.dimensions.join()||data.metricHeaders.map(x=>x.name).join()!==d.metrics.join()||data.rowCount<data.rows.length)throw new Error("GA4_INVALID_RESPONSE");
 const rows=data.rows.map(row=>{if(row.dimensionValues.length!==d.dimensions.length||row.metricValues.length!==d.metrics.length)throw new Error("GA4_INVALID_RESPONSE");const dims=row.dimensionValues.map(x=>x.value),v=dims[0]!;if(!/^\d{8}$/.test(v))throw new Error("GA4_INVALID_RESPONSE");dims[0]=`${v.slice(0,4)}-${v.slice(4,6)}-${v.slice(6)}`;if(!z.iso.date().safeParse(dims[0]).success||dims[0]!<start||dims[0]!>end||/[?#]/.test(dims.at(-1)!))throw new Error("GA4_INVALID_RESPONSE");if(report==="ga4-content-events"&&!/^(ci_.*|fhc_.*|line_oa_click)$/.test(dims[1]!))throw new Error("GA4_INVALID_RESPONSE");const metrics=row.metricValues.map(x=>{const n=Number(x.value);if(!/^\d+$/.test(x.value)||!Number.isSafeInteger(n)||n<0)throw new Error("GA4_INVALID_RESPONSE");return n;});if(report==="ga4-daily-organic"&&metrics[1]!>metrics[0]!)throw new Error("GA4_INVALID_RESPONSE");return Object.fromEntries(d.columns.map((c,i)=>[c,i<dims.length?dims[i]!:metrics[i-dims.length]!]));});
 return {columns:[...d.columns],rows,nativeTimeZone:data.metadata?.timeZone??null,truncated:data.rowCount>rows.length,limitations:[...(data.metadata?.subjectToThresholding?["GA4 thresholded report"]:[]),...(data.metadata?.dataLossFromOtherRow?["GA4 other-row loss"]:[]),...(data.metadata?.samplingMetadatas?.length?["GA4 sampled report"]:[]),"Scope: hostName ccpun.com/www.ccpun.com only; blog.ccpun.com excluded explicitly", "Daily native dates; no distinct-user summation; behavioral events are not confirmed leads; page event attribution is event location, not cohort conversion"],overview:[]};
}
export async function collectMarketingDaily(input:{source:"gsc"|"ga4";token:string;resource:string;end:string;start?:string}, fetchForReport:(report:AnalyticsReport)=>typeof fetch, deadline:number):Promise<Array<Partial<AnalyticsDataset>&Pick<AnalyticsDataset,"report"|"title"|"columns"|"rows">>> {
 if(deadline-Date.now()<20000)return[];
 const start=input.start??shiftAnalyticsDate(input.end,-55);
 if(input.source==="gsc")return(await Promise.all((["gsc-daily-page","gsc-daily-query-page"] as const).map(async report=>{try{const dimensions=report==="gsc-daily-page"?["date","page"]:["date","query","page"];const r=await fetchGscSearchAnalytics({siteUrl:input.resource,token:input.token,startDate:start,endDate:input.end,dimensions,rowLimit:25000},fetchForReport(report));return{report,title:report==="gsc-daily-page"?"GSC · รายวันต่อหน้า":"GSC · รายวันคำค้นต่อหน้า",windowStart:start,windowEnd:input.end,sourceAsOf:input.end,nativeTimeZone:"America/Los_Angeles",columns:["วันที่","หน้าเว็บ",...(report==="gsc-daily-query-page"?["คำค้น"]:[]),"คลิก","การแสดงผล","CTR (%)","อันดับเฉลี่ย"],rows:r.rows.map(row=>{const date=row.dimensions.date;if(!date||!z.iso.date().safeParse(date).success||date<start||date>input.end)throw new Error("GSC_INVALID_RESPONSE");return{"วันที่":date,"หน้าเว็บ":row.dimensions.page??"",...(report==="gsc-daily-query-page"?{"คำค้น":row.dimensions.query??""}:{}),"คลิก":row.clicks,"การแสดงผล":row.impressions,"CTR (%)":row.impressions?row.ctr*100:null,"อันดับเฉลี่ย":row.impressions?row.position:null};}),truncated:r.truncated,limitations:[r.limitation,"Final web data; page-only totals and query diagnostics are separate grains; no summation of overlapping report windows"]};}catch{return null;}}))).filter(x=>x!==null);
 const native=Promise.all((Object.keys(definitions) as Array<keyof typeof definitions>).map(async report=>{try{const d=definitions[report];const scopeFilter={filter:{fieldName:"hostName",stringFilter:{matchType:"FULL_REGEXP",value:"^(www\\.)?ccpun\\.com$",caseSensitive:false}}};const reportFilter={filter:{fieldName:report==="ga4-daily-organic"?"sessionDefaultChannelGroup":"eventName",stringFilter:{matchType:report==="ga4-daily-organic"?"EXACT":"FULL_REGEXP",value:report==="ga4-daily-organic"?"Organic Search":"^(ci_.*|fhc_.*|line_oa_click)$",caseSensitive:true}}};const body={dateRanges:[{startDate:start,endDate:input.end}],dimensions:d.dimensions.map(name=>({name})),metrics:d.metrics.map(name=>({name})),dimensionFilter:{andGroup:{expressions:[scopeFilter,reportFilter]}},orderBys:d.dimensions.map(dimensionName=>({dimension:{dimensionName}})),limit:"10000",returnPropertyQuota:true};const response=await fetchForReport(report)(`https://analyticsdata.googleapis.com/v1beta/properties/${input.resource}:runReport`,{method:"POST",headers:{Authorization:`Bearer ${input.token}`,"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(15000),cache:"no-store"});if(!response.ok)return null;return{report,title:report==="ga4-daily-organic"?"GA4 · Organic รายวันต่อหน้า":"GA4 · Intent activity รายวันต่อหน้า",windowStart:start,windowEnd:input.end,sourceAsOf:input.end,...normalizeMarketingGa4(report,await response.json(),start,input.end)};}catch{return null;}})).then(values=>values.filter(x=>x!==null));
 const campaign=(async()=>{const report="ga4-session-performance" as const;try{const body={...ga4MarketingRequest(report,start,input.end),dimensionFilter:{filter:{fieldName:"hostName",stringFilter:{matchType:"FULL_REGEXP",value:"^(www\\.)?ccpun\\.com$",caseSensitive:false}}}};const response=await fetchForReport(report)(`https://analyticsdata.googleapis.com/v1beta/properties/${input.resource}:runReport`,{method:"POST",headers:{Authorization:`Bearer ${input.token}`,"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(15000),cache:"no-store"});if(!response.ok)return[];const data=normalizeGa4Marketing(report,await response.json(),start,input.end);return[{report,windowStart:start,windowEnd:input.end,sourceAsOf:input.end,...data,limitations:[...data.limitations,"Scope: hostName ccpun.com/www.ccpun.com only; blog excluded. Native day × sessionSourceMedium × campaign × landing page; no event-to-session or business attribution inferred."]}];}catch{return[];}})();
 return(await Promise.all([native,campaign])).flat();
}

export async function collectMarketingWindow(source:"gsc"|"ga4",start:string,end:string,variables:Record<string,string|undefined>=process.env,fetcher:typeof fetch=fetch){
 const {beginMarketingWindow}=await import("./window-store");const {finishAnalyticsCollection}=await import("../analytics/store");const {getGoogleDataAccessToken}=await import("../seo-intelligence/google-data-auth");const {getSeoGoogleProviderReadiness}=await import("../seo-intelligence/provider-readiness");const {analyticsDatasetSchema,analyticsHash,sanitizeAnalyticsRaw}=await import("../analytics/model");
 const claim=await beginMarketingWindow(source,start,end,variables);if(claim.status!=="claimed")return{source,status:claim.status==="completed"?"duplicate":claim.status,batchId:claim.batchId,startDate:start,endDate:end};
 const raw:import("../analytics/model").RawAnalyticsPage[]=[];const collectedAt=new Date().toISOString(),deadline=Date.now()+85000;const fetchForReport=(report:AnalyticsReport):typeof fetch=>async(url,init)=>{const response=await fetcher(url,{...init,redirect:"error",signal:AbortSignal.any([...(init?.signal?[init.signal]:[]),AbortSignal.timeout(Math.max(1,deadline-Date.now()))])});if(response.ok){const body=sanitizeAnalyticsRaw(await response.clone().json());const requestMeta={path:new URL(url instanceof Request?url.url:String(url)).origin+new URL(url instanceof Request?url.url:String(url)).pathname,parameters:typeof init?.body==="string"?sanitizeAnalyticsRaw(JSON.parse(init.body)):{}};raw.push({report,page:raw.filter(x=>x.report===report).length,collectedAt,body,requestMeta,canonicalJson:JSON.stringify({body,requestMeta}),hash:analyticsHash({body,requestMeta}),origin:"provider-response"});}return response;};
 try{if(getSeoGoogleProviderReadiness(source,variables).status!=="manual-sync-ready")throw new Error("NOT_CONFIGURED");const token=await getGoogleDataAccessToken(variables,fetcher),resource=source==="gsc"?variables.CCPUN_GSC_SITE_URL!.trim():variables.CCPUN_GA4_PROPERTY_ID!.trim();const projected=await collectMarketingDaily({source,token,resource,start,end},fetchForReport,deadline);if(!projected.length)throw new Error("SOURCE_UNAVAILABLE");const reports=projected.map(value=>analyticsDatasetSchema.parse({source,resourceScope:resource,batchId:claim.batchId,collectedAt,sourceAsOf:end,overview:[],limitations:[],truncated:false,nativeTimeZone:null,windowStart:start,windowEnd:end,lastAttemptAt:collectedAt,lastAttemptStatus:"completed",rawHash:analyticsHash(raw.filter(x=>x.report===value.report).map(x=>x.hash)),...value}));const accepted=new Set(reports.map(x=>x.report));const expected:AnalyticsReport[]=source==="gsc"?["gsc-daily-page","gsc-daily-query-page"]:["ga4-daily-organic","ga4-content-events","ga4-session-performance"];const omittedReports=expected.filter(report=>!accepted.has(report));const status=await finishAnalyticsCollection({batchId:claim.batchId,attempt:claim.attempt,reports,raw:raw.filter(x=>accepted.has(x.report)),error:null},variables);return{source,status,batchId:claim.batchId,startDate:start,endDate:end,nextEnd:shiftAnalyticsDate(start,-1),reportCoverage:omittedReports.length||reports.some(r=>r.truncated)?"partial":"complete",omittedReports,reports:reports.map(r=>({report:r.report,rows:r.rows.length,truncated:r.truncated}))};}catch{await finishAnalyticsCollection({batchId:claim.batchId,attempt:claim.attempt,reports:[],raw:[],error:"source-unavailable"},variables);return{source,status:"failed",batchId:claim.batchId,startDate:start,endDate:end};}
}
