import { z } from "zod";
export const marketingWindowSchema = z.enum(["this_week", "last_week", "this_month", "last_month", "rolling_7", "rolling_28"]);
export type MarketingWindow = z.infer<typeof marketingWindowSchema>;
export type MarketingMetric = { metric: string; currentDenominator?: number | null; previousDenominator?: number | null; current: number | null; previous: number | null; absoluteChange: number | null; percentageChange: number | null; sampleStatus: "insufficient_data" | "low" | "sufficient"; coverageStatus: "complete" | "partial" | "insufficient_history"; freshnessStatus: string; threshold: number; unit: string; evidenceRef: string };
export const marketingMetricLabels: Record<string,string> = { organic_sessions:"เซสชันจาก Organic",search_clicks:"คลิกจาก Google",search_impressions:"การแสดงผลใน Google Search",line_clicks:"คลิกปุ่ม LINE · intent",calculator_complete:"ทำเครื่องมือคำนวณเสร็จ · intent",calculator_start:"เริ่มใช้เครื่องมือ",social_views:"ยอดดูตามแพลตฟอร์ม",sessions:"เซสชัน",qualified_conversations:"บทสนทนาที่มีคุณภาพ" };
export type MarketingContentRow = MarketingMetric & { rank: number; assetId: string; title: string; url: string | null; category: string | null; lifecycle: string; mappingStatus: "mapped" | "unmapped"; publishedAt: string | null };
export type MarketingLeaderboard = { id: string; title: string; metric: string; basis: string; platform: string | null; rows: MarketingContentRow[] };
export const marketingActionSchema = z.object({ id: z.string().uuid().optional(), version: z.number().int().min(0), assetId: z.string().max(200).nullable(), priority: z.enum(["high", "medium", "low"]), actionType: z.enum(["title", "description", "refresh", "cta", "internal_link", "expansion", "promotion", "keyword", "investigation"]), description: z.string().trim().min(1).max(2000), expectedMetric: z.enum(["organic_sessions", "search_clicks", "line_clicks", "calculator_complete", "social_views"]), owner: z.string().max(160), status: z.enum(["backlog", "planned", "doing", "measuring", "done"]), executedAt: z.string().datetime().nullable(), measurementDays: z.number().int().min(7).max(90), notes: z.string().max(2000), hypothesis: z.string().max(1000), confounderNotes: z.string().max(2000) }).strict();
export type MarketingActionInput = z.infer<typeof marketingActionSchema>;
export type MarketingAction = MarketingActionInput & { id: string; version: number; createdAt: string; updatedAt: string; baseline: number | null; result: number | null; absoluteChange: number | null; percentageChange: number | null; outcome: "improved_after" | "declined_after" | "inconclusive"; measurementStatus: string };
export type MarketingHealth = { source: string; report: string; sourceAsOf: string | null; collectedAt: string | null; lastSuccess: string | null; lastError: string | null; expectedLagDays: number; status: "fresh" | "expected_lag" | "stale" | "failed" | "unknown"; coverageStart: string | null; coverageEnd: string | null; timezone: string | null; limitations: string[] };
export type MarketingOpportunity = { id: string; area: string; assetId: string | null; title: string; priority: "high" | "medium" | "low"; evidenceRefs: string[]; recommendedAction: string; confidence: "low" | "medium"; reason: string };
export type MarketingManifest = { batchId: string; report: string; rawHash: string; periodStart: string | null; periodEnd: string | null; sourceAsOf: string | null; collectedAt: string; timezone: string | null; limitations: string[] };
export type MarketingContentPerformance = { assetId: string; title: string; url: string; category: string | null; topic: string | null; publishedAt: string | null; mappingStatus: "mapped" | "unmapped"; lifecycle: string; metrics: MarketingMetric[] };
export type MarketingCampaign = { sourceMedium: string; campaign: string; landingUrl: string | null; assetId: string | null; sessions: number; engagedSessions: number; keyEvents: number | null; coverageStatus: string; periodStart: string; periodEnd: string };
export type MarketingDashboard = { state: "ready" | "unavailable"; version: "marketing-v1"; generatedAt: string; window: { key: MarketingWindow; currentStart: string; currentEnd: string; previousStart: string; previousEnd: string; availability?: "mature_data" | "no_mature_data"; calendarPolicy: string }; kpis: MarketingMetric[]; contentPerformance: MarketingContentPerformance[]; campaigns: MarketingCampaign[]; benchmarks: Array<{ positionBand: string; cohortSize: number; medianCtr: number | null; definition: string }>; leaderboards: MarketingLeaderboard[]; trend: Array<{ date: string; metric: string; value: number }>; funnel: { mode: "activity-only"; steps: Array<{ event: string; count: number | null; status: string }>; limitation: string }; health: MarketingHealth[]; opportunities: MarketingOpportunity[]; actions: MarketingAction[]; manifest: MarketingManifest[]; notes: string[] };
export function normalizeMarketingUrl(value: string) {
  try { const url = new URL(value, "https://ccpun.com"); if (!["ccpun.com", "www.ccpun.com", "blog.ccpun.com"].includes(url.hostname) || !["https:", "http:"].includes(url.protocol)) return null; return `https://${url.hostname === "www.ccpun.com" ? "ccpun.com" : url.hostname}${url.pathname.replace(/\/+$/, "") || "/"}`; } catch { return null; }
}

export function marketingProviderEnd(source:"gsc"|"ga4",now=new Date(),timeZone=source==="gsc"?"America/Los_Angeles":"America/Los_Angeles"){const date=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).format(now);return new Date(Date.parse(date+"T00:00:00Z")-(source==="gsc"?3:1)*86400000).toISOString().slice(0,10);}
