import "server-only";
import { neon } from "@neondatabase/serverless";
import { adminOperationsRuntimeInputFromEnvironment, resolveAdminOperationsRuntimeIdentity } from "../operations/foundation";
import { marketingWindowSchema, marketingActionSchema, type MarketingDashboard, type MarketingWindow, type MarketingActionInput, type MarketingAction } from "./model";
function client(variables:Record<string,string|undefined>){if(!resolveAdminOperationsRuntimeIdentity(adminOperationsRuntimeInputFromEnvironment(variables))||!variables.CCPUN_ADMIN_DATABASE_URL?.trim())throw new Error("MARKETING_DATABASE_NOT_READY");return neon(variables.CCPUN_ADMIN_DATABASE_URL.trim(),{fetchOptions:{signal:AbortSignal.timeout(20000)}});}
export async function readMarketingDashboard(window:MarketingWindow="rolling_7",variables:Record<string,string|undefined>=process.env,cutoff=new Date().toISOString()):Promise<MarketingDashboard>{
 const key=marketingWindowSchema.parse(window);try{const rows=await client(variables).query("SELECT ccpun_admin.admin_read_marketing_v2($1,$2::timestamptz) AS data",[key,cutoff]);const data=rows[0]?.data;if(!data||data.version!=="marketing-v1"||!Array.isArray(data.kpis)||!Array.isArray(data.leaderboards))throw new Error("MARKETING_INVALID_RESPONSE");return data as MarketingDashboard;}catch{return{state:"unavailable",version:"marketing-v1",generatedAt:new Date().toISOString(),window:{key,currentStart:"",currentEnd:"",previousStart:"",previousEnd:"",calendarPolicy:"Unavailable"},kpis:[],contentPerformance:[],campaigns:[],benchmarks:[],leaderboards:[],trend:[],funnel:{mode:"activity-only",steps:[],limitation:"Data unavailable; no fabricated zeros"},health:[],opportunities:[],actions:[],manifest:[],notes:["Marketing analytical store unavailable; existing analytics exports remain available."]};}
}
export async function saveMarketingAction(input:MarketingActionInput,variables:Record<string,string|undefined>=process.env):Promise<MarketingAction>{const parsed=marketingActionSchema.parse(input);if(["measuring","done"].includes(parsed.status)&&!parsed.executedAt)throw new Error("INVALID_MARKETING_ACTION");const rows=await client(variables).query("SELECT ccpun_admin.admin_save_marketing_action($1::jsonb) AS data",[JSON.stringify(parsed)]);return rows[0]?.data as MarketingAction;}
export async function syncMarketingIdentity(input:unknown[],variables:Record<string,string|undefined>=process.env){const rows=await client(variables).query("SELECT ccpun_admin.admin_sync_marketing_identity($1::jsonb) AS data",[JSON.stringify(input)]);return Number(rows[0]?.data);}
